[FE] Study Record MSW 구현
woowacourse-teams/2023-haru-study pull request #108
Opened 2023-07-19 09:20 UTC by nlom0218

## 관련 이슈
  closed #46

## 구현 기능 및 변경 사항

- 임시 useFetch() 훅 생성
   - 두 개의 인자(url, config 객체)를 받음
   - data와 status(fulfilled, pending, rejected)를 반환
- 스터디 기록 관련 msw 작성

2023-07-19 16:41 UTC, yeopto requested changes
useFetch는 괜찮은데, msw가 좀 달라서!

일단 코멘트 확인 해주세용~~ 고생하셨슴다. 노-아.

2023-07-19 16:41 UTC, yeopto commented on frontend/src/hooks/useFetch.ts
> +export default useFetch;
이 부분에 대해서 내일 이야기 해보죠!
저는 일단 api 디렉토리에 `request`란 공용 api util 함수를 구현해서 이용했습니다.
지금은 겹치는 일이 없을 것 같으니 머지되어도 괜찮을 것 같아요.

2023-07-19 16:41 UTC, yeopto commented on frontend/src/mocks/worker.ts
> +export const worker = setupWorker(...handlers, ...studyRecordHandlers);
저도 제가 만든 handler를 추가해주긴 했는데요.

`mocks` 디렉토리에 `handlers`란 디렉토리를 만들고 `handlers` 안에 `index.ts`를 만들어 그 곳에 각자가 만든 hanlders.ts를 추가해주면 어떨까요?

예시는 다음과 같습니다.

```ts
// index.ts
import { studyMakinghandlers } from './studyMakingHandler';
import { 새로만든 핸들러 } from ./새로만든 핸들러

export const handlers = [...studyMakinghandlers, ...새로만든  핸들러];

```

그럼 `worker.ts` 와 `server.ts` 는 다음과 같이 작성하는거죠

```ts
// worker도 이하 동문

import { setupServer } from 'msw/node';

import { handlers } from './handlers';

export const server = setupServer(...handlers);
```

저는 일단 위 방식대로 만들어놨어요~ 이야기 한번 해보시죠! 정해지면 둘 중 한명꺼 일단 머지하고, 거기에 맞게 수정 뒤 남은 사람도 머지하는하면 될 것 같습니당

2023-07-20 00:46 UTC, nlom0218 commented on frontend/src/hooks/useFetch.ts
> +export default useFetch;
네! 함께 데이터 패칭하는 거 이야기 나누고 2차 데모 끝나고는 해당 함수 혹은 훅으로 데이터 통신을 해보면 좋을 거 같아요!

2023-07-20 00:47 UTC, nlom0218 commented on frontend/src/mocks/worker.ts
> +export const worker = setupWorker(...handlers, ...studyRecordHandlers);
아하! `handlers`을 한 곳에서 모아두고 `server`, `worker`엔 하나의 `handlers`만 불러오는 거 군요! 좋은 방법이에요!

2023-07-20 02:08 UTC, woo-jk approved these changes
GOOD

2023-07-20 02:08 UTC, woo-jk commented on frontend/src/hooks/useFetch.ts
> +const useFetch = <T extends object>(url: string, config: RequestInit = {}) => {
config는 옵셔널하게 받아도 되지 않을까요?

2023-07-20 05:23 UTC, nlom0218 commented on frontend/src/hooks/useFetch.ts
> +const useFetch = <T extends object>(url: string, config: RequestInit = {}) => {
`config`은 넘겨주지 않아도 됩니다! 하지만 넘겨주지 않는다면 `{}`가 기본값이 되어요!

2023-07-20 06:13 UTC, yeopto approved these changes
굳

2023-07-20 06:14 UTC, merged