[BE] PomodoroRoom 관련 테스트 및 리팩터링
woowacourse-teams/2023-haru-study pull request #235
Opened 2023-08-02 07:06 UTC by aak2075

## 관련 이슈

- closed: #232 
## 구현 기능 및 변경 사항

- [x] 추가된 V2(Controller, Service)에 대한 테스트 추가
- [x] 기존에 사용하던 Controller, Service 및 관련 테스트 @Deprecated 처리

2023-08-02 08:27 UTC, jaehee329 requested changes

2023-08-02 08:27 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/integration/PomodoroRoomIntegrationTest.java
> +        MvcResult result = mockMvc.perform(get("/api/v2/studies?participantCode=" + participantCode.getCode())
https://stackoverflow.com/questions/17972428/mock-mvc-add-request-parameter-to-test
`requestParam`은 `.param`으로 쓰면 깔끔하더라고요, map으로 묶어서 넣을 수도 있고..
변경하진 않아도 괜찮습니다!

2023-08-02 08:27 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceV2Test.java
> +}
여기 뭔가가 이상한데요? 끝에 뭐가 빠진 것 같은 느낌..

2023-08-02 08:41 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/integration/PomodoroRoomIntegrationTest.java
> +        MvcResult result = mockMvc.perform(get("/api/v2/studies?participantCode=" + participantCode.getCode())
저도 param 쓰는 쪽이 깔끔한 거 같아용

2023-08-02 08:52 UTC, woosung1223 reviewed
고생하셨읍니다.

2023-08-02 08:52 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/integration/PomodoroRoomIntegrationTest.java
> +        MvcResult result = mockMvc.perform(get("/api/v2/studies?participantCode=" + participantCode.getCode())
저도 `param` 쓰는 쪽이 깔끔한 것 같더라고요!

2023-08-02 08:52 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceV2Test.java
> +
여기서 영속성 컨텍스트를 FLUSH + CLEAR 해줘야 실제 쿼리가 다 나갈 것 같은데 어떻게 생각하시나요!

2023-08-02 08:52 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/integration/PomodoroRoomIntegrationTest.java
> +        MvcResult result = mockMvc.perform(get("/api/v2/studies?participantCode=" + participantCode.getCode())
베리 좋은 방식이라 반영 했습니다👍

2023-08-02 08:55 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceV2Test.java
> +
동의합니다 1차 캐시에서 찾아오기 보다 비우고 실제 쿼리를 날리는게 좋겠네요

2023-08-02 08:58 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/room/service/PomodoroRoomServiceV2Test.java
> +}
IDE가 일을 안하네요

2023-08-02 15:26 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java
findStudy, findRoom 메서드 명을 통일을 해줘야 할 것 같습니다.
동일하게 PomodoroRoomResponseV2 dto를 통해 반환되는데 다른 이름이면 안될 것 같아요!
해당 부분에 주석이 안달려서 파일 리뷰로 남깁니다.

2023-08-02 15:51 UTC, MoonJeWoong requested changes
고생했어요 마코! 크게 리뷰할 부분이 없었는데 컨트롤러 쪽 study와 room 네이밍 부분만 잘 통일해서 수정해주면 좋을 것 같습니다!

2023-08-02 23:43 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/room/controller/PomodoroRoomControllerV2.java
오~ 빠뜨렸군요!! 컨트롤러여서 study로 통일해줬습니다

2023-08-03 02:07 UTC, woosung1223 approved these changes

2023-08-03 02:07 UTC, jaehee329 approved these changes

2023-08-03 02:08 UTC, MoonJeWoong approved these changes

2023-08-03 02:08 UTC, merged