[BE] PomodoroProgress 관련 테스트 및 리팩토링
woowacourse-teams/2023-haru-study pull request #236
Opened 2023-08-02 08:13 UTC by jaehee329

## 관련 이슈

closed #231 

## 구현 기능 및 변경 사항

- PomodoroProgress 관련 테스트 추가
- 진행도 `proceed()` 관련 로직 오류 수정
- 예외 이름 변경

2023-08-02 08:15 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/content/service/PomodoroContentService.java
> +            throw new IllegalProgressStateException();
여긴 오류 이름이 추상적이고 어떤 상황에서 쓰는 오류인지 알 수가 없어서 바꿨어요~

2023-08-02 08:16 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
> +    }
beforeEach로 fixture를 필드에 가져가는 것보다 그냥 몇 줄 적어서 메서드마다 로컬로 쓰게 하는게 깔끔한 것 같아서 이렇게 했어요~

2023-08-02 08:49 UTC, aak2075 approved these changes
꼼꼼하게 잘 해주셨네요👍
Enum length 코멘트 남긴 부분만 확인해주시면 좋을 것 같습니다!

2023-08-02 08:49 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
> +                                .param("memberId", Long.toString(member.getId()))
.param 좋은데요?👍
그냥 경로에 ?로 붙여줬는데 이렇게 바꿔야겠네요

2023-08-02 08:49 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
> +        int notDoneStatusCount = 3;
`PomodoroStatus`에서 `DONE`을 제외한 개수이기 때문에
`PomodoroStatus.values().length - 1` 로 설정하는건 어떤가요?

2023-08-02 08:49 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/progress/repository/PomodoroProgressRepositoryTest.java
> +                pomodoroRoom);
이름으로 생성하는 쿼리 메소드도 테스트해주셨네요!👍

2023-08-02 08:49 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceV2Test.java
> +        //
then이 빠진것 같네용

2023-08-02 08:59 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/progress/service/PomodoroProgressServiceV2Test.java
> +        //
ㅋㅋㅋ 착한 사람 눈에만 보입니다

2023-08-02 09:06 UTC, woosung1223 reviewed
고생하셨읍니다.

2023-08-02 09:06 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
> +        entityManager.persist(pomodoroProgress);
FLUSH + CLEAR 하는 건 어떻습니까

2023-08-02 09:06 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
> +        });
소프트하네요

2023-08-02 09:06 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
> +        PomodoroProgress pomodoroProgress = new PomodoroProgress(pomodoroRoom, member);
ProgressIntegrationTest이고 `ParticipantCode`, `PomodoroRoom`, `Member`는 테스트마다 변경사항이 없기 때문에 `@BeforeEach` 로 넣으면 깔끔할 것 같아요~ 근데 제 취향이라 참고만

2023-08-02 09:06 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
> +        // when & then
컨벤션이 when, then 이었던거같아여

2023-08-02 16:43 UTC, MoonJeWoong requested changes
고생했어요 모디! 테스트 부분에서 새로운 걸 정말 많이 배워가네요 ㅎㅎ 로직 잘못된 부분만 다시 수정해봐요~

2023-08-02 16:43 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
>      }
아프겠네요... 😢

2023-08-02 16:43 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/integration/PomodoroProgressIntegrationTest.java
> +                                .param("memberId", Long.toString(member.getId()))
mock신이시군요 모디...

2023-08-02 16:43 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/progress/repository/PomodoroProgressRepositoryTest.java
> +                .getEntityManagerFactory().getPersistenceUnitUtil();
DataJpaTest에서는 영속성 컨텍스트 상태를 이런 방식으로 확인해볼 수 있군요! 좋은 포인트 잘 배워가요~ 👍

2023-08-02 16:43 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
> +        pomodoroProgress.proceedV2();
proceedV2 수정한 로직에 잘못된 부분이 있어서 테스트가 제대로된 방식으로 동작하지 않는 것 같습니다.
현재 방식에서 디버깅 찍고 돌려보면 첫 cycle에서 done으로 바로 넘어가버리고 다시 plan으로 돌아가지 못하네요... 😭

2023-08-02 16:43 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
> +            currentCycle++;
여기 currentCycle++하고 getNext 같이 해줘야 할 것 같습니다!

2023-08-03 01:10 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/progress/domain/PomodoroProgress.java
> +            currentCycle++;
맞네요~ 변경하고 해당 테스트 반영도 했습니다~

2023-08-03 01:18 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
> +        int notDoneStatusCount = 3;
원래 PomodoroStatus.values().length로 했었는데 DONE 추가로 인한 예외적인 상황이 하나 생긴거잖아요,
1 자체도 매직 넘버가 될거같은데 차라리 이것까지 빼거나
아니면 차라리 3이라고 명시적으로 쓰는 편이 나아보여서 이렇게 했습니다~ 
DONE이 예외적인 것도 해당 enum 내에 있을 게 아닌 상위 레이어에서나 아는 정보니까요

2023-08-03 01:37 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/progress/domain/PomodoroProgressTest.java
> +        pomodoroProgress.proceedV2();
위에는 해결됐는데 아래는 무슨 말씀인지 잘 이해를 못했어요!

2023-08-03 02:07 UTC, woosung1223 approved these changes

2023-08-03 02:09 UTC, MoonJeWoong approved these changes

2023-08-03 02:14 UTC, merged