[BE] 스웨거 예외 응답 명세 추가
woowacourse-teams/2023-haru-study pull request #312
Opened 2023-08-11 08:07 UTC by aak2075

## 관련 이슈

- closed: #310
## 구현 기능 및 변경 사항

- 스웨거 예외 응답 전용 커스텀 어노테이션 추가
- 스웨거 상세 명세 추가

## 스크린샷(선택)

2023-08-12 03:22 UTC, jaehee329 requested changes
결과물 보니 시간 들인 보람이 있긴 하네요~

컨트롤러마다 이제 exception을 명시해야 하는 건 조금 아쉽지만 Swagger를 사용하기로 했으니 어쩔 수 없겠죠 ㅠㅠ

고생하셨고 pr #324 도 한번 확인해주세요~

2023-08-12 03:22 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/config/swagger/SwaggerConfig.java
> +                });
이 클래스의 메서드 사용 순서에 따른 정렬과
여기에 try~catch 구문을 좀 더 깔끔하게 만들 수 있을 것 같아서 pr #324 로 한번 제안해봤습니다!
확인 부탁드릴게요

2023-08-12 04:24 UTC, MoonJeWoong reviewed
커스텀 어노테이션을 사용해서 API 명세까지 깔끔하게 해주셨네요. 시간이 많이 드는 작업이셨을텐데 고생많으셨습니다! 사소한 부분 리뷰드렸는데 확인하고 merge하면 될 듯 합니다!

2023-08-12 04:24 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/config/swagger/OpenApiConfiguration.java
> +                .version("v2.0.0")
저희 버저닝을 2.0으로 하기로 한게 맞나요? api에는 v2라고 붙여두기는 했지만 저희 릴리즈 버저닝은 1.x.x 이렇게 가자고 얘기가 나왔었던 것 같은데 프론트와 같이 얘기해보면 좋을 것 같습니다!

2023-08-12 04:24 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/ExceptionMapper.java
> +                ExceptionSituation.of("스터디 참여 기록이 없습니다.", NOT_FOUND));
스터디 참여 기록이라고 하면 content와 겹쳐지는 의미로 전달될 여지가 있을 것 같습니다. "해당 스터디에 참여한 상태가 아닙니다." 정도로 수정해보는 건 어떤지 제안드려봐요!

2023-08-12 04:24 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/member/controller/MemberControllerV2.java
> +    @Deprecated
deprecated가 점점 늘어나네요... 얼른 로그인 기능까지 릴리즈 하고 없애버리고 싶네요 😭

2023-08-12 06:06 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/config/swagger/OpenApiConfiguration.java
> +                .version("v2.0.0")
Swagger 버전으로 릴리즈 버전을 사용해도 나쁘지 않을 것 같네요!
일단 프로덕트 버전 따라가도 될 것 같습니다.

2023-08-12 06:09 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/common/ExceptionMapper.java
> +                ExceptionSituation.of("스터디 참여 기록이 없습니다.", NOT_FOUND));
반영했습니다 👍 확실히 의미가 중복되긴 하네요!

2023-08-12 14:57 UTC, MoonJeWoong approved these changes
변경사항 확인 후 Approve 합니다 :)

2023-08-13 04:06 UTC, woosung1223 approved these changes

2023-08-13 07:36 UTC, aak2075 commented
![image](https://github.com/woowacourse-teams/2023-haru-study/assets/35948985/aaedd4d2-463d-4ef6-a74b-ad2a0f952cf4)

스웨거에 dev 서버 설정 추가 했습니다.

2023-08-13 08:35 UTC, jaehee329 approved these changes

2023-08-13 08:36 UTC, merged