[BE] 참여코드 만료 기능 구현
woowacourse-teams/2023-haru-study pull request #442
Opened 2023-08-24 15:35 UTC by jaehee329

## 관련 이슈

close #367 
## 구현 기능 및 변경 사항

- [x] 인메모리 Repository를 통해 일정 시간이 지나면 자동으로 참여코드가 만료되는 기능을 구현한다.
- [x] 참여 코드 조회 및 만료 시 Repository에서의 객체 탐색 시간 복잡도가 O(1)이 되도록 한다.
- [ ]  @Schedule에 대한 테스트를 포함한다.

---
아직 테스트가 구현되지 않았습니다. 주말에 해당 내용을 추가할 예정이며 시간이 있는 지금 만료 처리를 위한 Repository를 먼저 제안해 함께 고민해보는게 팀적으로 좋을 것 같아서 PR을 먼저 만들었습니다.

아래는 고민한 내용들입니다.
_Redis 바로 썼으면 이런 고민 안 했겠는데..._

---
### 1.
처음에는 스케줄을 통해 참여 코드를 List 혹은 Map으로 단순히 관리하며 O(n)으로 순회하며 오래된 값을 삭제하려 함
List의 경우 save()는 문제가 없으나 findByCode() expireCode()에서 만료 시간 정책이 길어졌을 때 성능적 손해가 너무 큼
그보다 나은 Map<String, ParticipantCode>는 findByCode()에서는 우수하나 여전히 expireCode()과정에서 entrySet으로 순회를 해야 함.

### 2.
이를 보완하기 위해 두 개의 자료구조를 필드로 가지는 구조로 넘어감.
Map<String, ParticipantCode> participantCodeRepository = new HashMap<>();
Queue<ParticipantCode> participantCodeQueue = new LinkedList<>();

세 개의 주요 메서드에서 시간복잡도가 기존보다 우수하나 동시성 문제를 굉장히 해결하기 어렵게 됨.

두 자료구조를 util.concurrent 의 자료구조를 사용하더라도 문제는 여전함.
예를 들어 save()를 할 때 Repository와 Queue에 동시에 값을 넣어주어야 하므로 결국 synchronize를 비롯한 Lock의 개념을 도입할수밖에 없음.

### 3.
쓰기가 발생하는 메서드에 synchronize를 쓰면 가장 간단하지만 성능은 조금 아쉬움.
예를 들어 expireCode()를 통해 두 자료구조의 조회 및 수정이 반복문 내부에서 이루어지는데 해당 메서드를 아래처럼 묶어버리면 반복문이 이뤄지는 동안 다른 스레드에서 자료구조에 접근이 불가능해짐.
```
@Scheduled(fixedDelay = SCHEDULE_DELAY_IN_MILLIS)
protected synchronized void expireCode() {
    while (!participantCodeQueue.isEmpty() && participantCodeQueue.peek().isExpired()
) {
	ParticipantCode first = participantCodeQueue.poll();
        participantCodeRepository.remove(first.getCode());
    }
}

```

### 4.
락을 더 정교하게 사용하기 위해 읽기 락과 쓰기 락을 구분해서 사용할 수 있는 `ReentrantReadWriteLock` 을 선택함.
`ReentrantReadWriteLock`은 읽기 락은 여러 스레드에 의해서 동시에 점유될 수 있지만 쓰기 락은 하나의 스레드만 점유할 수 있음.
또한 읽기 락과 쓰기 락은 배타적, 읽기 락이 점유 중일 때 쓰기 락의 점유가 불가능하며 반대도 동일하다.

이를 통해 현재 제시하는 코드에서는 `ReentrantReadWriteLock`을 통해 락 점유를 용도에 따라 구분하고 범위를 최소화한다.

### 5.
마지막으로 고민될 수 있는 부분으로 쓰기 락은 유일하므로 save() 요청에 대한 처리 성능이 일반적인 락보다 조금 떨어질 수 있다.
`ReadWriteLock`이 아닌 일반 락의 경우 여러 스레드의 scheduling 방식이 균등하다고 가정했을 때 읽기와 쓰기에 관계없이 요청에 대한 처리 성능이 비슷한 수준으로 낮아짐을 예상할 수 있다.

하지만 `ReadWriteLock`을 사용하는 경우 읽기와 쓰기 요청 수준이 비슷하고 두 종류의 요청들이 매우 많이 몰렸을 때 읽기 락은 동시에 여러 스레드에 의해 점유되어 처리되고, 이에 반해 배타적인 쓰기 락을 요청하는 스레드들은 모두 대기하고 더 낮은 확률로 락을 점유하게 된다.
따라서 일반 락을 사용하는 경우보다 save() 혹은 스케줄에 의한 expireCode() 처리하는 스레드의 성능은 더 낮을 것으로 예상된다.

다행히 서비스의 플로우를 고려했을 때 참여 코드의 저장 로직(save())은 호출 빈도가 조회 로직(findByCode())과 차이가 많이 난다. 또한 만료된 참여 코드를 제거하는 스케줄 로직도 서버 내부적으로 처리되어 성능 문제에서 비교적 자유로우므로 `ReentrantReadWriteLock`의 사용은 적절하다고 여겨진다.

2023-08-24 15:37 UTC, jaehee329 commented
임시로 Draft PR로 전환했고 이후 테스트 추가되면 살리겠습니다~

2023-08-24 17:28 UTC, woosung1223 commented
굿 고생하셨습니다 👍

다만 개인적인 궁금점이 몇 가지 있는데요! 답변 달아주시면 감사하겠습니다~

---
1. 

List로 관리하는 게 성능적인 측면에서 부담이 될 수 있을 것 같아 자료구조를 이중으로 관리한다고 하셨는데, Binary Search Tree에 대해서는 어떻게 생각하시나요?

비즈니스적으로 '생성', '삭제' 보다는 조회 성능이 중요한 상황이기에 BST가 충분히 합당한 선택지가 될 수도 있을 것 같아요~ Lock을 따로 관리할 필요도 없기 때문에 간단해져서 개발 + 유지보수 비용을 낮출 수도 있을 것 같구요!

현재 구현해주신대로 자료구조를 이중으로 사용하는 방식도 좋아보이긴 합니다!


2.

동시성 보장이 되어야 하는 이유에 대해 조금 더 설명해주실 수 있을까요? 

Queue의 경우 오로지 만료 로직을 처리하기 위해서 사용되는 것 같은데, 이는 사용자가 접근할 수 있는 부분도 아니어서.. 동시성 문제가 발생하지 않을 것 같은데 혹시 제가 놓친 부분이 있을까요? 

HashMap에는 데이터가 들어갔지만 Queue에는 데이터가 들어가지 않은 상황에서 Queue에 있는 데이터를 조회할 일이 없지 않냐는 의미입니다!

2023-08-25 03:38 UTC, jaehee329 commented
의견 감사합니다~
우선 이미 필요한 내용은 만들어두었고 여유가 며칠 있으니 팀원들이 다같이 이 기간에 해당 내용 수용만 가능하다면 더 필요한 내용은 단기적으론 없을 듯 해 생산성 문제는 없어보여요!
1. BST 단독으로 사용하는 것은 전에 테오와 잠시 고민했던 것처럼 HashMap 단일로 쓰는 방식과 비슷하게 느껴집니다. 물론 성능적인 부분들은 만들어놓고 서비스 특성에 맞게 성능 테스트를 하는 편이 가장 좋으나 여기는 시간이 따로 꽤 필요하고요. 다만 두 자료구조의 특성 상 아시다시피 삽입은 차치하고 스케줄에 의한 만료된 코드 삭제를 위해 전체 순회를 할 때 성능적 손해가 커 이중으로 사용하는 방향이 나을 것 같습니다.

사실 작은 규모에서는 뭘 써도 크게 문제될 것은 없지만 자료구조를 이중으로 사용하면 동시성을 제외하고는 성능적으론 우수하니 굳이 안 쓸 이유도 없다는 생각이 들어서요 ㅎㅎ 성능 테스트는 해봐야겠지만요

2. 동시성 문제는 자료구조를 하나만 쓰든, 두개를 쓰든 inMemory를 선택한 시점에서 모두 고민해야만 합니다. 말씀처럼 현재는 사용자의 데이터 접근은 Map을 통해 일어나므로 Queue에 데이터를 넣는 시점이 달라지는 것은 엄청 위험한 수준은 아닙니다. 당장은 삭제가 스케줄을 통해 이뤄지므로 만료되었음에도 삭제 처리가 되지 않는 경우 정도 발생할 수 있겠네요.  
하지만 서비스의 방향이 타이머 동기화까지로 잡힌 상황에서 스터디가 시작되면 코드를 만료시키는 등의 외부에서 데이터 삭제 요청을 할 수 있게 되는 시점엔 크리티컬한 문제가 발생할 수 있을 듯 합니다!
단일 자료구조를 사용한다면 당연히 Concurrent 계열을 사용해야 하구요.

당연히 생산성과 성능을 저울질하며 개발해야 하는데 시간 있는 시점에 성능 쪽에 투자를 좀 하는 것도 괜찮아보이고, 또 수평 확장 외에도 이런 동시성 문제가 쌓여서 명령어를 단일 스레드로 처리하는 Redis 도입을 해야 하는 이유가 될 수도 있고요

2023-08-25 03:53 UTC, aak2075 requested changes
많은 고민들을 하신 것이 느껴지네요 👍

바로 Redis를 도입하고 싶어지네요ㅋㅋㅋㅋㅋ 도입한다면 고민거리도 달라질 것 같기도 하고요

락을 사용하는 것과 자료구조를 두 개 사용하는 이유에 대해 궁금한 부분이 있어서 코멘트 남겼으니 확인 부탁드릴게요~

> 예를 들어 save()를 할 때 Repository와 Queue에 동시에 값을 넣어주어야 하므로 결국 synchronize를 비롯한 Lock의 개념을 도입할수밖에 없음.

값을 동시에 넣어주는 것은 Lock이 아닌 Transaction으로 해결해야할 문제가 아닐까요? 물론 빈으로 등록되는 `InMemoryParticipantCodeRepository` 내의 컬렉션은 변경이 되고 여러 스레드에서 참조할 수 있어 동시성 문제가 발생하는것에는 동의를 합니다.
다만, ParticipantCode는 비즈니스적으로 동시성 문제가 발생하더라도 문제가 없다고 생각하는데 스케쥴링으로 지속적으로 수행되는 작업에 대해 락을 거는 비용에 대비해서 얻는 이득이 무엇이 있나요?

2023-08-25 03:53 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
> +    private LocalDateTime createdDate;
요 부분은 @Transient인 이유가 있을까요? Repository에서도 ParticipantCode를 꺼내서 isExpired() 메서드를 사용할 때 createdDate 변수가 사용되는데요, 인메모리에서 직접 관리할 때는 괜찮지만 만약 Redis나 영속화하게 되는 경우 조회시createdDate가 없어서 문제가 될 것 같습니다.

2023-08-25 03:53 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepository.java
> +    }
Queue를 순차적으로 순회하며 만료가 된 요소까지 삭제하는 로직인데요, 어차피 순차적으로 탐색하기 때문에 이것도 O(n)이라고 생각이 듭니다. 만약 똑같이 O(n)이 맞다면 자료구조를 두 개를 사용하면서 그에 따른 문제를 고려하기 보다 LinkedHashMap으로 하나로 관리하는게 편하지 않을까 생각합니다.

2023-08-25 04:45 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepository.java
> +    }
순차 순회이긴 한데 범위 탐색만 가능하냐가 가장 큰 성능 차이일 것 같아요! 그러면 O(n)이 아니니까요
처음에 LinkedHashMap을 쓰는 방식도 고민했었는데 Queue처럼 맨 앞의 값만 탐색이 가능한지를 몰라서 두 개의 자료구조를 쓰는 방향으로 틀었는데, 다시 찾아보니 LinkedHashMap의 entrySet이 삽입 순서가 보장된다는 javadoc 내용이 있는 것 같네요~ 좀 더 확인해보고 여기에 Concurrent하게 만들어서 사용하는 방향으로 틀어볼게요

2023-08-25 04:48 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/participantcode/domain/ParticipantCode.java
> +    private LocalDateTime createdDate;
Redis 사용 시 만료에 대한 처리가 너무 간단하게 아래처럼 적어주기만 하면 되서 createdDate 자체가 필요가 없게 되서요, 당장은 Repository에서 직접 만료시키기 위해 필요하긴 한데 후에는 그럴 필요가 아예 없을 듯 해서 transient를 썼습니다
```
@TimeToLive
private Long expirationPeriod;
```

2023-08-25 05:16 UTC, jaehee329 commented
마코 덕분에 LinkedHashMap을 사용하는 방식으로도 다시 한번 고민해볼게요!
https://stackoverflow.com/questions/2923856/is-the-order-guaranteed-for-the-return-of-keys-and-values-from-a-linkedhashmap-o
1. Transaction 사용과 Lock은 성격이 많이 다릅니다.
Transaction을 구현하기 위한 도구가 Lock인데요, 현재는 DB의 저장 또는 조회의 결과와 성공 실패 여부가 외부 DB 서버에서 한 번에 오잖아요? 결국 성공 실패 응답이 오기까지 해당 스레드가 대기를 해야 하므로 lock의 관점에서는 넓은 범위의 lock을 걸어둔 것과 같습니다.
이는 지금의 구조에선 서비스 레이어에서 호출하는 repository레이어의 save()메서드에 synchronized를 걸어서 사용하는 것과 같네요. 그렇게 되면 락의 범위가 넓어지므로 성능이 더 저하되고요.
2. 참여 코드의 동시성 문제에 대해 물으신 건 크게 서비스 레이어 수준에서 봤을 땐 삭제와 조회 시점이 미묘하게 다른 건 비즈니스적으로는 문제가 되지 않아요. 하지만 문제가 되는 것은 Repository Class에서의 데이터 관리인데 이 부분은 concurrent class를 쓰는 것과 아닌 것의 차이이므로 굳이 말하지 않아도 이미 아실 것 같네요.

락을 사용하면서 오는 성능 저하는 락 자체의 성능과 관계가 되는데 ReentrantReadWriteLock 자체의 락과 언락 부분을 살펴보시면 굉장히 간결합니다. mutex와 유사하고요.
concurrent한 자료구조를 쓰는 것에는 당연히 이해하실 것 같은데, 해당 자료구조들에도 결국 내부를 살펴보면 부분적인 synchronized 블록이 있어요. 결국 동시성에 대해 **우리가 명시적으로 lock을 통해 제어해주냐 아니면 이미 synchronized가 내장된 concurrent class를 쓰느냐**의 문제인데, 제가 제안한 코드는 두 개의 자료구조를 쓰기 때문에 그걸 외부에서 명시적으로 해줘야 하는 것이었고, 말씀처럼 LinkedHashMap을 concurrent하게 감싸서 사용하면 이 기능이 내장되므로 할 필요가 없게 되겠죠!

아쉽게도 concurrent linked HashMap은 없어 감싸서 사용하다보니 결국 제가 직접 락을 건 것 처럼 성능 차이는 있을 수밖에 없겠네요
https://stackoverflow.com/questions/1391918/does-java-have-a-linkedconcurrenthashmap-data-structure

2023-08-25 08:31 UTC, woosung1223 commented
사실 아직 성능이 무엇이 우세하다는 확신은 없는데(테스트를 해봐야겠죠) 방장이 참여코드를 만려시키는 등의 기능을 고려하신거라면 충분히 납득 가능한 구현이라고 생각됩니다~

인메모리로 관리하는 방식이다보니 Heap 메모리 사용량이 걱정되는 부분도 있는데 일단 현재 시점에서는 큰 문제는 없을 것 같습니다! 이건 만료 기간이 길어진다면 논의해볼만하다고 생각해요 (일주일 등..)

테스트까지 올려주시면 확인하고 Approve 드리겠습니다! 👍

2023-08-25 08:42 UTC, aak2075 commented
1. 현재 상황에서 트랜잭션을 구현하기 위해서 락을 사용하는게 맞습니다. 트랜잭션이든 Lock이든 둘 다 Lock을 사용해야하기 때문에 제가 얘기헀던 `Lock이 아닌 트랜잭션`은 잘못 말한것 같네용. `save()를 할 때 Repository와 Queue에 동시에 값을 넣어주어야 하므로 결국 synchronize를 비롯한 Lock의 개념을 도입할수밖에` -> 데이터 정합성을 보장해야 하는데 동시성 제어를 위해 Lock이 필요했다 라고 느껴져서 이야기했는데 해결하고자 하는 문제는 동시성 문제 같네요.

말씀해주신대로 concurrent linked HashMap이 없는것이 아쉽네요. 따라서 직접 lock을 걸어줘야 할 것 같습니다.
ReentrantReadWriteLock를 사용하여 직접 lock을 컨트롤하는 것이 간결하기는 하나 그래도 혹~시 모를 휴먼 에러가 발생할 가능성이 있어서 특정 코드 블럭만 락을 컨트롤할 것이 아니라면 synchronized 키워드가 낫다고 생각하는데 어떻게 생각하시나요?

저도 lock을 거는것에는 동의를 해서 테스트 올려주시면 approve 할게요~
이 주제 재밌네용 👍 고생많으십니다~!

2023-08-27 06:11 UTC, MoonJeWoong commented
슬랙에서 얘기했던 내용 기록으로 남겨두기 위해 comment 남깁니다. 

일단 테스트도 테스트인데 따로 극단적인 성능 최적화가 당장 필요한게 아니면 구현되어있는 자료구조를 사용하는게 맞다는 생각이 듭니다. 슬랙에서 모디가 말해준 논점이 Synchronized(LinkedHashMap())을 사용할 것인지, 아니면 ConcurrentHashMap을 사용할 것인지 인 것 같은데요. 맨 처음 말했던 것처럼 당장 극단적인 성능 최적화가 필요한 게 아니라면 ConcurrentHashMap으로 구현해두고 약간의 성능개선 단계로 Synchronized(LinkedHashMap())이나 모디가 올려준 자료구조 2개에 락을 직접 구현해주는 방식으로 순차적인 단계를 밟으면서 성능개선을 해나가는게 맞지 않을까 합니다.

저도 ConcurrentHashMap을 쓰면 순차 순회를 해야한다는 건 맘에 걸리긴 하는데... 이건 뭔가 만료된 참여코드를 삭제하는 로직을 개선해야 하지 않을까 싶은 생각도 드네욤... 이건 나중에 생각 좀 정리해서 함 공유해보겠습니다.

2023-08-30 23:46 UTC, MoonJeWoong approved these changes
고생 많으셨습니다 모디! 깊은 고민을 같이 해볼 수 있도록 먼저 의견 제시해주셔서 감사합니다 덕분에 많이 또 배워가네요. 코멘트도 딱히 할만한 부분은 현재로서는 없는 것 같아서 approve 하도록 할게요~

2023-08-31 01:27 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepositoryTest.java
> +        assertThat(map).hasSize(51);
저도 이게 참 고민이 되더라구요~ 서비스적으로는 전혀 쓰일 일이 없는 메서드인데 만들어야 할까? 아니면 없는 채로 리플렉션을 쓸까?
물론 리플렉션까지 쓰는 테스트 로직이 저희와 친숙하지 않아서 더 고민되기도 하고요.
당장은 임시로 쓰는 클래스와 테스트라 그냥 둬도 될거같기도 하고요!

다른 분들은 어떠신가요?

2023-08-31 01:38 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepositoryTest.java
> +        assertThat(map).hasSize(51);
저라면 valid 한 참여코드 한 개, expired 된 참여코드 한 개를 넣어두고 findByCode로 검증할 것 같아요
49개, 51개 넣어주는 방식도 실제 상황과 유사하게 테스트할 수 있어서 좋은 것 같지만, 한 개 씩만 넣어도 경계값은 테스트하는 것 같아서요~
리플렉션을 사용하지 않을 수도 있고요

2023-08-31 01:40 UTC, aak2075 approved these changes

2023-08-31 01:40 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepositoryTest.java
> +        assertThat(map).hasSize(51);
히이로 의견대로 책임을 가지는 것은 이상하지는 않으나 제 생각은 그래도 프로덕션 코드가 테스트 코드에 의존해서 사용하지 않는 코드가 추가되는 것은 관리하기 어렵다는 생각이 듭니다.
이외의 선택지로는 이미 있는 메서드인 findByCode로 일일이 삭제가 됐는지 안됐는지 확인할 수 있겠지만 모디가 작성해준 형태가 이해하기도 쉽고 간결한 것 같아서 저는 적절히 사용했다는 생각이 드네요~

2023-08-31 01:47 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/participantcode/repository/InMemoryParticipantCodeRepositoryTest.java
> +        assertThat(map).hasSize(51);
크루들이 제시해준 방법에서는 findByCode 방식으로 검증을 하긴 했을 것 같은데 모디가 해준 것처럼 리플렉션을 통한 검증 방식을 팀에서 채택한다고 하면 저는 그대로 가져가도 좋을 것 같습니다!

2023-08-31 02:21 UTC, merged