Be/feature/301 slack logging alert
woowacourse-teams/2023-haru-study pull request #449
Opened 2023-08-27 15:41 UTC by MoonJeWoong

## 관련 이슈

- closed #301 

## 구현 기능 및 변경 사항

- Internal Server Error, 500에 해당하는 예상하지 못한 예외 발생 시 슬랙 알림 메세지를 요청하는 로거 기능 구현

## 작업 과정 정리

2023-08-27 15:45 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/SlackAppender.java
> +            "src\\main\\resources\\submodule\\application.properties";
리뷰해주실 때 이 절대 경로 잘 적용되는지 한 번씩 확인 부탁드립니다!

2023-08-29 08:32 UTC, woosung1223 reviewed
고생하셨습니다~ slack 알림 기능 붙으니 좋네요 ㅎㅎ 코멘트에 대해서는 의견 남겨주세요!

2023-08-29 08:32 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/common/logging/SlackAppender.java
> +            "src\\main\\resources\\submodule\\application.properties";
요거 URL 어플리케이션에서 관리 안하는 방법 없을지 고민이 되네요.

아니면 SlackAppender 자체를 빈으로 등록하고 yml에서 가져오는 방식은 어떨까요?
스프링에서 관리할 필요가 없는 객체를 빈으로 등록한다는 점은 아쉽긴 합니다!

2023-08-29 08:32 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/common/logging/SlackAppender.java
> +    }
Map.of 부분을 메소드로 분리해도 깔끔할 것 같아요~

```java
return Map.of("blocks", List.of(headerBlock(), messageBlock(), footerBlock()));
```

2023-08-29 08:32 UTC, woosung1223 commented on backend/src/main/resources/slack-appender.xml
> +  <appender name="ASYNC_SLACK_APPENDER" class="ch.qos.logback.classic.AsyncAppender">
AsyncAppender를 사용하신 이유가 있을까요?

2023-08-29 08:32 UTC, woosung1223 commented on backend/src/main/resources/slack-appender.xml
> +    <neverBlock>false</neverBlock>  <!-- LoggingEvent queue가 가득 찼을 때 다른 로깅 스레드가 block 되지 않고 log를 누락시키며 application이 blocking되지 않도록 합니다 -->
알아본 바에 의하면 `neverBlock`가 false로 설정되는 경우 queue가 가득 찼을 때 queue에 공간이 생길 때까지 대기하게 되므로 어플리케이션이 해당 작업을 기다리게 될 수 있다고 해요.

주석에서 설명하는 내용과는 다른 것 같아 여쭤봅니다.

ref: https://logback.qos.ch/manual/appenders.html

2023-08-30 16:47 UTC, jaehee329 requested changes
로깅 관련 인터페이스를 구현하여 사용하는 방향에 대해선 고민해보지 못했는데 블로그 및 PR을 보고 흥미로운 접근이라 느꼈습니다!

전에 간단한 내용의 해당 이슈를 올린지 오래되어 제 의도가 옅어지기도 했고 최근에 히이로가 로그에 대해 깊게 공부한 것의 영향으로 로깅의 연장선으로 해당 기능의 구현을 시도하신게 아닐까 하는 생각이 들었습니다.
PR을 읽고 난 뒤  아직 `에러에 대한 슬랙 알림을 왜 Logback을 통해 구현해야 할까`에 대한 의문이 남아있습니다.

만드신 appender에서 하는 기능은 url로 string 형태의 body를 POST로 쏘는 일입니다. 이건 Logback을 통해서 할 작업인지는 의문입니다. 
1. 로깅 프레임워크를 선택하는 최우선순위 중 하나는 가벼움이라고 알고 있습니다. 현재는 하는 웹 요청에 대한 작업까지 포함되어, 연속적으로 로그가 발생하는 상황에서 성능 병목이 크게 예상됩니다. 스프링은 기본적으로 한 요청에 대해서는 싱글스레드로 동작하므로 더 신경쓸 필요가 있습니다. 블로그에 적으셨다시피 로깅 파일은로그가 섞이는 것을 방지하기 위해 synchronized를 사용, 단 하나의 요청 처리 스레드만 접근하므로 성능에 굉장히 취약합니다. 추가로 RestTemplate을 쓰면 블로킹으로 호출되어 더 치명적이고요.
2. 이렇게 Logback을 통한 알림 처리 시 기능이 빈약하고 확장성도 떨어진다 생각합니다. 만약 Production 서버에 실제로 오류가 발생하는 코드가 머지되었다고 가정할 때, 실사용자가 많은 서비스라면 해당 오류가 초당 셀 수 없을 정도로 많이 발생할 것입니다. 이 때 이런 방식으로 서버가 구현되어있다면 아마 슬랙이 알림으로 금방 도배될 것입니다. Grafana의 알림은 이러한 상황에 대응이 가능한데요, datasource를 PromQL을 통해 시간 정보를 활용하기 때문에 특정 시간 구간에 수많은 오류가 발생해도 우리가 커스텀한 수의 알림만 보낼 수 있습니다. 이 부분은 Logback만으로는 해결이 불가능할 것 같습니다. 즉 기능은 하지만 실사용성이 떨어지는 알림 시스템이라고 여겨집니다.

만약 꼭 서버에서 슬랙으로 요청을 보내고자 한다면 이는 advice 클래스에서 에러 핸들링 과정에서 비동기식으로 이벤트를 처리하는 방법으로 요청을 보내는 것이 성능적으로 적절할 것 같습니다.

근본적으로 슬랙 webhook을 사용해 알림을 보내는 것은 모니터링 서버에서 해야 할 일이라 여겨집니다.
관리자에게 알림을 보내는 것은 '로그 남기기'의 일환일까요 아니면 '모니터링'의 일환일까요? 저는 후자라고 생각합니다. 이미 로깅-모니터링 시스템을 구축한 상황에서 그라파나는 시간 당 어떤 로그에 대해 어떻게 처리할지 강력한 알림 기능을 가지고 있습니다. 이러한 방향을 고민해보심은 어떨까요?

---
구현에 많은 시간이 들었을 PR에 길게 의문을 표하게 되어 미안한 마음이 큽니다.
저 또한 어떻게 히이로에게 이 많은 말들을 전달할지 오랜 시간 고민했음을 이해해 주세요.

문제를 알고 있으나 노력을 들였으니 운영 코드에 머지시켜 제 마음 한 켠에 기억나는 애매한 코드가 되기보다
히이로가 본질적인 문제 해결 방법을 다시 고려해보는게 더 도움이 될 것 같아 건조한 어투로 길게 리뷰 남깁니다.

해당 알림 기능은 추후에 Grafana를 통해 구현하거나 이 내용을 저에게 설득시켜주세요 ㅎㅎ

2023-08-31 01:53 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/logging/SlackAppender.java
> +            e.printStackTrace();
요거는 기능만 집중해서 구현하다보니 놓친 부분이네요... 캐치 감사합니다~ 👍

2023-08-31 02:02 UTC, MoonJeWoong commented on backend/src/main/resources/slack-appender.xml
> +    <neverBlock>false</neverBlock>  <!-- LoggingEvent queue가 가득 찼을 때 다른 로깅 스레드가 block 되지 않고 log를 누락시키며 application이 blocking되지 않도록 합니다 -->
이건 새벽에 구현하다가 주석만 달아두고 바꾸지 못했나봅니다... 말씀해주신대로 true로 수정되는 방향이 맞습니다!

2023-08-31 02:06 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/logging/SlackAppender.java
> +            FileReader fileReader = new FileReader(ResourceUtils.getFile(PROPERTIES_PATH));
알림 기능 구현 자체에만 집중하다보니 이런 디테일을 놓치고 생각하지 못했네요~ 감사합니다!

2023-08-31 02:13 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/logging/SlackAppender.java
> +                String.class); //Slack에 알림 메세지를 전송한다
해당 부분은 restTemplate을 사용한 특별한 이유가 있었다기 보다는 해당 기능을 구현하기 위해 일단 사용한 부분이 컸습니다! restTemplate과 webClient의 차이에 대해서는 잘 숙지하고 있지 못한 부분이었는데 덕분에 다시 인지하게 되었네요. 만약 해당 코드를 리팩토링 했다면 비동기적 요청 처리와 통일성 유지 측면에서 webClient로 바꾸는 방향이 옳다고 생각합니다~

2023-09-03 02:26 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/logging/SlackAppender.java
> +            "src\\main\\resources\\submodule\\application.properties";
1,3. 다시 알아보니 윈도우의 경우 `\\`와 `/`를 모두 경로 구분자로 적용 가능하고 맥과 리눅스에서는 `/`를 사용한다고 하네요. 해당 부분은 `/`로 수정되어야 하는 것이 맞습니다.

2. 처음 기능 구현 당시 yml 파일에서 값을 읽어오려면 스프링 컨텍스트에서 읽어와야만 하는 줄 알고 빈으로 등록되지 않았던 Appender에서는 값을 읽는게 불가능하다고 판단했었습니다. 그런데 properties 확장자 파일에서 값을 읽어오는 방식으로 똑같이 yml 파일에서도 읽기가 가능하더라구요~ 그래서 말씀해주신대로 각 profile 별 yml 파일에서 관리하는 방향으로 갈 수 있을 것 같습니다!

2023-09-03 02:28 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/logging/SlackAppender.java
> +            "src\\main\\resources\\submodule\\application.properties";
추가적으로 logback-extension 모듈을 추가로 사용하면 관련 구성요소들도 빈으로 등록할 수 있는 것 같더라구요. 해당 부분은 재미삼아 참고하시라고 [레퍼런스](https://github.com/qos-ch/logback-extensions/wiki/Spring) 남겨두겠습니다!

2023-09-03 02:40 UTC, MoonJeWoong commented
레벨4에 들어가면 더 바빠질 일정 속에서 슬랙 알림과 같이 우선순위가 떨어지는 기능 구현이 힘들어질 것 같아 방학 중 혼자 구현해본 기능이었습니다. 생각보다 많은 시간과 노력을 들였던 부분이나 해당 부분은 팀원들과 사전에 이러한 방향으로 구현하자고 논의가 이뤄졌던 게 아니라 개인적인 학습과 도전을 위해 시도해본 것이 맞습니다. 그러다 보니 좀 더 다양한 선택지를 고려하지 못한 방향으로 기능 구현이 이뤄지기도 했었던 것 같습니다. 그럼에도 불구하고 정성스럽게 리뷰해준 크루들에게 많이 감사합니다. 덕분에 더 넓은 시야에서 다시 문제를 고민해볼 수 있는 기회도 얻을 수 있었습니다. 

한 편으로는 저의 개인적인 시도로 인해 리뷰하면서 고민이 많았을 [모디](@jaehee329)에게도 미안한 마음을 전하고 싶습니다. 덕분에 정말 많은 것들을 다시 생각하고 배울 수 있는 기회가 되었습니다. 감사합니다. 😄 

해당 PR은 팀에서 논의된대로, 그라파나 slack 알림 등의 기능을 구현하는 방향으로 변경하기 위해 close 하도록 하겠습니다!

2023-09-03 02:40 UTC, closed without merging