Fe/refactor/464 errorhandling
woowacourse-teams/2023-haru-study pull request #503
Opened 2023-09-13 07:48 UTC by yeopto

## 관련 이슈

## 구현 기능 및 변경 사항

- 

## 스크린샷(선택)

2023-09-14 07:59 UTC, nlom0218 reviewed
고생했어요 엽토! 👍

몇 가지 저의 생각을 리뷰로 남겼으니 확인해주세요:)

2023-09-14 07:59 UTC, nlom0218 commented on frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
> +  const { mutate, isLoading } = useCreateStudy(studyName, totalCycle, timePerCycle);
mutate보다 실제 어떤 동작을 하는지 네이밍을 통해 나타내면 좋을 듯 해요! (다른 곳에서도요!)

2023-09-14 07:59 UTC, nlom0218 commented on frontend/src/components/participation/PrticipationContents/PartcipationContents.tsx
> +};
이와 같은 부분은 `if()`문을 통해 분리하면 어떨까요?

2023-09-16 04:12 UTC, yeopto commented on frontend/src/components/create/CreateStudyForm/CreateStudyForm.tsx
> +  const { mutate, isLoading } = useCreateStudy(studyName, totalCycle, timePerCycle);
반영했습니다~

2023-09-16 04:12 UTC, yeopto commented on frontend/src/components/participation/PrticipationContents/PartcipationContents.tsx
> +};
반영했어요~

2023-09-16 04:46 UTC, yeopto commented on frontend/src/components/participation/PrticipationContents/MemberRestart/MemberRestart.tsx
> +
요 부분은 hook으로 따로 안감싸줬는데, SSE 들어가면 어짜피 삭제될 로직이라 이렇게 해줬습니다 일단

2023-09-16 05:11 UTC, yeopto commented on frontend/src/components/participation/hooks/useCheckProgresses.ts
> +};
이 훅의 리턴을 result로 안하고 데이터를 명시적으로 해보려했는데, 아무래도 result가 pending일땐 undefined다 보니까 분기처리를 해서 리턴을 하도록 하다보니 사용처에서 복잡해지더라구요. 방법 아시는 분은 알려주시면 감사하겠습니다.

2023-09-16 06:29 UTC, nlom0218 commented on frontend/src/components/participation/PrticipationContents/MemberRegister/MemberRegister.tsx
> +import useRegisterProgress from '@Components/participation/hooks/useRegisterProgress';
`@Components` 에서 훅으로 불러오고 있는데, 확인해보실 수 있을가요?

2023-09-16 06:32 UTC, nlom0218 approved these changes

2023-09-16 06:32 UTC, woo-jk requested changes
굳 고생했어요~ 코멘트 확인 부탁드립니닷

2023-09-16 06:32 UTC, woo-jk commented on frontend/__test__/CreateStudyPage.test.tsx
GOOD

2023-09-16 06:32 UTC, woo-jk commented on frontend/src/api/index.ts
> +  timePerCycle: StudyTimePerCycleOptions | null,
이거 null로 요청보내면 안되지 않나요? 사용하는 곳에서 타입가드해줘야 할 듯 합니다.

2023-09-16 06:32 UTC, woo-jk commented on frontend/src/components/participation/hooks/useCheckProgresses.ts
> +    { suspense: true },
suspense 기본값이 true라서 옵션 빼도 될 것 같아요~

2023-09-16 06:32 UTC, woo-jk commented on frontend/src/components/participation/hooks/useCheckProgresses.ts
> +  }
```js
if(!studyId) throw new Error('잘못된 접근입니다.'):
```

2023-09-16 07:14 UTC, yeopto commented on frontend/src/api/index.ts
> +  timePerCycle: StudyTimePerCycleOptions | null,
음 이 부분은 totalCycle과 timePerCycle 초기 값이 Select 컴포넌트 초기 상태값이라 값이 null 입니다.

기존 mutation을 적용해주지 않았을 때는 훅에서 인자를 받을 수 있는 요청 함수를 리턴했고 그 함수를 클릭 이벤트 함수에서 사용했기에 저 부분에 대해 타입가드를 할 수가 있었습니다.

하지만 mutation을 쓰면서 훅 인자로 주입해주고 있어서 만약 `if(!totalCycle &&  !timePerCycle) throw Error`나 return을 하다보면 개설하기 페이지에 접근했을 때 totalCycle과 timePerCycle 초기값이 null이라 에러바운더리에 걸려 fallback만을 보여주게 되거나 아무것도 뜨지 않게됩니다. 

studyName 인자 같은경우는 useCreateStudyForm에서 null일 경우 빈 문자열을 주고 있어요. 마찬가지로 totalCycle과 timePerCycle이 null 일때 어떠한 기본 값을 주고 싶었는데 이거 타입 자체가 number나 string이 아닌 특정한 숫자가 오는 union 타입이라 기본값을 union 타입에 추가하는건 또 아닌거 같아서 명시적으로 null로 하는 것이 맞겠다는 생각을 했고 어쩔 수 없이 null이 들어올 수 있도록 해주었습니다.

사실 UI적으로 null일때는 요청하는 버튼이 disabled가 되어서 요청할 일이 없을거에요. 하지만 개발자 도구에서 유저가 disable를 풀고 요청한다면 문제일텐데, 그 때는 서버측에서 잘못된 값이 가서 에러를 넘겨줄거기에 저희가 에러를 보여줄 수 있다고 생각합니다.

혹시나 더 좋은 방안이 있다면 알려주세용 :)

2023-09-16 07:15 UTC, yeopto commented on frontend/src/components/participation/PrticipationContents/MemberRegister/MemberRegister.tsx
> +import useRegisterProgress from '@Components/participation/hooks/useRegisterProgress';
도메인 관련된 훅들은 컴포넌트 하위의 hook으로 옮겨줘서 정상입니다!

2023-09-16 07:16 UTC, yeopto commented on frontend/src/components/participation/hooks/useCheckProgresses.ts
> +    { suspense: true },
반영했습니당~

2023-09-16 07:16 UTC, yeopto commented on frontend/src/components/participation/hooks/useCheckProgresses.ts
> +  }
요것도 반영했어요~

2023-09-16 07:28 UTC, woo-jk commented on frontend/src/api/index.ts
> +  timePerCycle: StudyTimePerCycleOptions | null,
아 넵 이해했습니다~! 어프루브 할게요!

2023-09-16 07:29 UTC, woo-jk approved these changes
👍

2023-09-16 07:32 UTC, merged