Fe/feature/43 button component
woowacourse-teams/2023-haru-study pull request #51
Opened 2023-07-14 06:32 UTC by nlom0218

## 관련 이슈
  closed #43 

## 구현 기능 및 변경 사항
- Button 컴포넌트 구현
- CircularProgress 컴포넌트 구현

## 스크린샷(선택)

2023-07-14 06:40 UTC, yeopto requested changes
노아~ 코멘트 남긴부분만 수정 부탁드려요~

2023-07-14 06:40 UTC, yeopto commented on frontend/src/components/Button/Button.tsx
> +type StyledButtonProps = Omit<Props, 'text' | 'handleClick'>;
요 부분 수정 부탁드립니다!

2023-07-14 07:12 UTC, woo-jk commented on frontend/src/components/Button/Button.tsx
> +  size: Size;
size 속성은 optional로 받고 기본 값을 medium으로 하면 어떨까요?

2023-07-14 07:21 UTC, nlom0218 commented on frontend/src/components/Button/Button.tsx
> +type StyledButtonProps = Omit<Props, 'text' | 'handleClick'>;
네 :)

`StyledButtonProps` 을 제거하고 `Props`를 재사용할 수 있도록 했어요!

2023-07-14 07:22 UTC, nlom0218 commented on frontend/src/components/Button/Button.tsx
> +  size: Size;
좋은 의견이네요. `medium`이 가장 많이 사용되니까 기본값으로 설정할게요!

2023-07-14 08:45 UTC, woo-jk commented on frontend/src/components/Button/Button.tsx
> +  $style?: CSSProp;
variant 속성과 concept 속성의 특징이 서로 유사해보여요. concept 속성을 variant로 흡수 시키면 어떨까요?

그리고 studying, retrospect 명칭은 도메인 용어에 가까워서 공통 컴포넌트에 사용하기는 부적절해보입니다!

2023-07-14 10:20 UTC, nlom0218 commented on frontend/src/components/Button/Button.tsx
> +  $style?: CSSProp;
네! 도메인 용어 고민해봐야겠어요!

2023-07-15 13:25 UTC, yeopto approved these changes
확인했어요~ 머지할게요~!

2023-07-15 13:25 UTC, merged