[BE] 스터디 진행 관련 기능을 스터디로 이동
woowacourse-teams/2023-haru-study pull request #522
Opened 2023-09-16 12:50 UTC by aak2075

## 관련 이슈

- closed: #521 

## 구현 기능 및 변경 사항

- [x] participant -> study로 필드 이동 및 api 응답 수정
    - [x] currentCycle
    - [x] step
    - [x] proceed()
    - [x] step api 응답시 스터디 방 상태와 진행 플로우로 나눠서 반환
- [x] next-step api participant -> study로 이동
    - [x] study의 step 및 currentCycle을 변경하도록 수정
- [x] step에 상태 추가
- [x] Content 현재 사이클의 Plan 및 retrospect 쓰는 로직 수정
    - [x] 현재 사이클을 participant -> study에서 가져오도록 수정

--- 

StudyIntegrationTest 일부 살렸는데 Code와 관련한 부분은 바뀔꺼라 안건드렸습니다.
step에 상태가 추가되고 `StudyResponse` 에서 스터디 방 상태와 진행도 상태로 분기해서 따로 반환하도록 했습니다.
next-step은 SSE이벤트 발행 관련 및 방장인지 확인하는 로직 추가해야돼서 TODO남겼습니다.
크게 바뀐건 없고 기존에 사용하던 로직만 옮겼으니 확인해주세용

2023-09-23 06:47 UTC, woosung1223 approved these changes
고생했습니다~

SSE는 이제 room마냥 추억으로 자리잡게 됐네요..

progress -> participant로 바뀌면서 네이밍이 모호한 부분이 보이긴 하는데 이 부분은 개별 작업하면서 자연스럽게 수정될 것 같습니다!

2023-09-24 03:44 UTC, MoonJeWoong requested changes
발표하러 다녀온 사이에 많이 바뀌었네요 ㅎㅎ... 고생 많으셨습니다 마코! 수정해야할 부분이나 사소하긴 하지만 팀원들과 얘기해봐야 할 부분들에 코멘트 달아뒀는데 확인 부탁드려요~

2023-09-24 03:44 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
> +import harustudy.backend.participant.exception.StudyStepException;
이 예외 클래스는 이제 Study 패키지로 이동시켜줘도 되겠다 싶었는데 에러코드 변경 문제가 있네요... 다른 크루들 의견이 궁금합니다.

2023-09-24 03:44 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/content/service/ContentService.java
> +    private List<Participant> getParticipantIfAuthorized(AuthMember authMember, Long studyId) {
```suggestion
    private List<Participant> getParticipantsIfAuthorized(AuthMember authMember, Long studyId) {
```
participants s가 빠진것 같아요~

2023-09-24 04:31 UTC, jaehee329 requested changes
짜잘이 수정 빠르게 하고 분업 해보죠~
귀찮은 작업 해주셔서 감사합니당

2023-09-24 04:31 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/study/service/StudyService.java
> +            return StudiesResponse.from(List.of(pomodoroStudy));
이 클래스에만 pomodoro 키워드가 아직 남아있네요!

2023-09-24 15:17 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/study/service/StudyService.java
> +            return StudiesResponse.from(List.of(pomodoroStudy));
바꿔놓고 커밋을 안했었네요ㅋㅋㅋㅋ 감사합니다

2023-09-24 15:17 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/study/service/StudyService.java
> +    private StudiesResponse findPomodoroStudyByMemberId(Long memberId) {
다 수정했습니다

2023-09-24 15:18 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/study/dto/StudyResponse.java
> +    }
말씀해 주신 부분이 맞는 것 같습니다. 수정했습니다

2023-09-24 15:19 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/common/exception/ExceptionMapper.java
> +import harustudy.backend.participant.exception.StudyStepException;
요건 그때 테오랑 한번 이야기했었는데 프론트에 변경이 가는 거라 일단 두는 쪽으로 이야기했던 것 같습니다

2023-09-25 06:00 UTC, jaehee329 approved these changes

2023-09-25 06:02 UTC, MoonJeWoong approved these changes
고생많으셨습니다!

2023-09-25 06:03 UTC, merged