[BE] 카카오 OAuth 인증 추가
woowacourse-teams/2023-haru-study pull request #605
Opened 2023-09-30 17:14 UTC by aak2075

## 관련 이슈

- closed: #598
## 구현 기능 및 변경 사항

- [x] OAuthClient 추상화
- [x] 카카오 OAuth 추가

잘 동작하는지 테스트하려면 포스트맨으로 다음과 같은 api 요청을 통해  할 수 있습니다.

1. 인증 코드 발급
https://kauth.kakao.com/oauth/authorize?client_id=d74b680a7a0dd13a1b7fe2e8456848d4&redirect_uri=http://localhost:8080/auth&response_type=code

2. 로그인 요청
http://localhost:8080/api/auth/login
{
    "oauthProvider": "kakao",
    "code": "발급 받은 코드"
}

2023-10-02 13:42 UTC, woosung1223 approved these changes
고생하셨습니다 양평대가 마선생님 컴포지트 패턴 야무지게 적용하셨네요 굿 자잘한 리뷰 달았는데 확인해주세요~

2023-10-02 13:42 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/CompositeOauthClient.java
> +public class CompositeOauthClient implements OauthClient{
공백이 하나 들어가야겠군요

2023-10-02 13:42 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/util/OauthWebClient.java
> +        return requestOauthUserInfo(userInfoUri, accessToken, Collections.emptyMap());
오버로딩 굿입니다.

2023-10-02 13:42 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/util/OauthWebClient.java
> +                                .map(OauthServerException::new))
콜백함수를 등록해서 예외를 전환시키셨군요 👍

2023-10-02 13:42 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/KakaoOauthClient.java
> +    public static final Map<String, List<String>> USER_INFO_PARAMETER = Map.of("property_keys",
접근제어자가 public인 이유가 있나용?

2023-10-02 13:42 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/KakaoOauthClient.java
> +        return oauthWebClient.requestOauthUserInfo(userInfoUri, accessToken, USER_INFO_PARAMETER);
USER_INFO_PARAMETER를 지정하지 않고 요청을 보내면 카카오에서는 어떤 응답을 내려주나요?

현재 구글 Oauth 요청의 경우 별다른 파라미터를 설정하지 않고 보내고 그 중에서 저희가 필요한 정보만 뽑아서 쓰는 걸로 알고 있어서요!

만약 지정하지 않아도 별 문제가 없다고 한다면 일관성을 위해 제거해도 괜찮을 것 같고, 카카오 측에서 규정 상 파라미터를 강제하고 있다면 구글쪽에서도 넣어주면 좋을 것 같다는 생각이 들었읍니다.

2023-10-02 13:42 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
> +        System.out.println("로그인_정보 = " + 로그인_정보);
?!

2023-10-02 13:54 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/CompositeOauthClient.java
> +public class CompositeOauthClient implements OauthClient{
+++ 추가로

secret ID까지 적용하는거 어떻게 생각하시나요?
카카오는 REST API를 사용한다면 선택적으로 적용할 수 있다고 하는데 구글도 secret ID를 쓰고 있는 입장에서 추가해도 좋지 않을까 싶네용

2023-10-02 13:58 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/KakaoOauthClient.java
> +        return oauthWebClient.requestOauthUserInfo(userInfoUri, accessToken, USER_INFO_PARAMETER);
지정하지 않으면 모든 데이터를 응답하며 문제는 없습니다.
[공식 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#propertykeys)
네트웍 비용을 생각해서 필요한 정보만 요청했는데 사실 오는 데이터도 몇 개 없어서 차이도 없을 것 같고 일관성을 택하는 쪽이 괜찮아 보이네요

2023-10-02 14:00 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/acceptance/AcceptanceTest.java
> +        System.out.println("로그인_정보 = " + 로그인_정보);
?!

2023-10-02 16:02 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/CompositeOauthClient.java
> +public class CompositeOauthClient implements OauthClient{
좋습니다. 조만간 추가하겠습니다.

2023-10-04 01:34 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/CompositeOauthClient.java
> +public class CompositeOauthClient implements OauthClient{
추가 완료.

2023-10-04 01:34 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/KakaoOauthClient.java
> +    public static final Map<String, List<String>> USER_INFO_PARAMETER = Map.of("property_keys",
없어용

2023-10-04 06:02 UTC, MoonJeWoong requested changes
고생하셨습니다 마코!
이제 카카오 Oauth 로그인도 가능해지겠네요 ㅎㅎ
OauthWebClient 클래스의 requestOauthUserInfo 부분만 예전처럼 body 없이 전체를 요청하는 방향으로 통일되기만 하면 좋을 것 같습니다!

2023-10-04 06:47 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/common/exception/HaruStudyException.java
> +    }
좋습니다!

2023-10-04 09:54 UTC, MoonJeWoong approved these changes
변경사항 반영 확인했습니다. 고생하셨어요~ 👍

2023-10-04 11:05 UTC, jaehee329 requested changes
안녕하세요 마코~
구조 깔끔하게 잘 잡아서 구현해주신 것 같아요!
Composite 패턴 및 에러 핸들링 잘 보았습니다!
코멘트 남긴 부분만 한번 더 확인해주세요~

2023-10-04 11:05 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/CompositeOauthClient.java
> +public class CompositeOauthClient implements OauthClient {
```suggestion
@RequiredArgsConstructor
@Component(value = "oauthClient")
public class CompositeOauthClient implements OauthClient {
```

맨 처음 보았을 때 왜 이 클래스는 Bean으로 등록하지 않지? 라는 생각이 들었는데 다른 Config 파일에서 등록해주고 있었군요!
어차피 이름을 통해 CompositeOauthClient를 찾는 것이 불가피하다면 설정 파일을 분리하는 방향보다 이 클래스에서 `@Component(value = ?)`로 바로 이름을 지정하여 등록해서 변경 포인트를 줄이는 방향은 어떻게 생각하시나요?

만약 설정 파일을 유지하게 된다면 그것대로 또 설정 파일의 위치를 어떤 패키지에 두어야 할 지 다시 고민하게 될 것 같습니다!

2023-10-04 11:05 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/KakaoOauthClient.java
> +    }
여기도요!

2023-10-04 11:41 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/CompositeOauthClient.java
> +package harustudy.backend.auth.infrastructure;
굉장히 어려운 질문이네요ㅋㅋㅋㅋ
OauthClient는 객체인가부터 시작해서 수 많은 생각들이 들었는데요, 
도메인이란 문제 해결의 영역이고 말씀해주신것처럼 비즈니스 로직을 담고 있기 때문에 도메인 하위로 들어가는 것이 옳은것 같네요.
패키지명도 oauth와 관련한 도메인이니 그냥 oauth로 변경했습니다.
날카로웠습니다👍

2023-10-04 11:43 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/util/OauthUserInfoExtractor.java
> +    KAKAO("kakao") {
enum의 상수끼리도 개행을 해주어야 하나요? 현재 사용하고 있는 다른 enum은 그러지 않고 있어서요

2023-10-04 11:50 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/infrastructure/CompositeOauthClient.java
> +public class CompositeOauthClient implements OauthClient {
좋은 생각입니다!

저도 configuration 파일이나 빈에대한 고민이 있었는데 덕분에 훨씬 간단해졌습니다 👍

2023-10-05 06:35 UTC, merged