[BE] 날짜 기반 스터디 기록 조회를 위한 view 전용 API 구현
woowacourse-teams/2023-haru-study pull request #611
Opened 2023-10-03 13:26 UTC by MoonJeWoong

## 관련 이슈

- closed #606 

## 구현 기능 및 변경 사항

- 날짜를 기반으로 멤버의 스터디 기록을 페이지 조회하는 기능
  - 날짜가 없으면 멤버의 전체 스터디 기록을 페이지 조회하는 기능
- 달력 기반으로 멤버의 날짜 별 스터디 기록을 조회하는 기능

## 참고용 API 명세
- [팀 노션 페이지](https://notion.so/04f4170327814866abf8e526f1e855bd?v=09f4633ee86d46c8bc403100802d112d&p=439068959a5f472aaf934a8a65a9ee09&pm=c)

2023-10-03 16:13 UTC, aak2075 requested changes
많은 것을 해주셨군요!
조인 쿼리에 대한 고민이나 페이징에 대한 고민도 많으셨을 텐데 고생 많으셨습니다!
덕분에 머릿속에서 사라졌던 페이징 공부도 할 수 있었습니다👍
시간이 없어서 다 보지는 못했지만 페이징 관련한 코멘트만 남기고 내일 추가로 리뷰 남기겠습니다!

2023-10-04 05:42 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/view/service/ViewService.java
> +                pageRequest);
저도 마코 말에 동의합니다~ PageRequest안에 Sort 객체가 포함되어 있어서 간단하게 구현할 수 있을 것 같아요!

그러면 StudyRepository에서 메서드를 두 개 만들지 않아도 되겠네요 ㅎㅎ

2023-10-04 05:43 UTC, aak2075 requested changes
많고 복잡한 기능이었는데 고생하셨습니다!

sql 파일 import 부분은 for문으로 createdDate.plusDays()와 같은 방식으로 Study 엔티티 생성해서 persist하는 방식으로도 가능은 할 것 같습니다. sql 파일을 사용하지 않고 테스트에서 직접 persist하는 것을 컨벤션으로 맞췄던것 같습니다. 우선순위가 높지는 않아서 바쁘다면 이슈파놓고 미뤄두는것도....?

startDate와 endDate에 대한 예외 처리는 400 + 에러코드 정의해 놓으면 될 것 같습니다. 아마 프론트에서는 분기처리할 게 없어서 에러코드는 굳이 알려주지 않아도 될 것 같고 400만 내려주면 준비된 에러 페이지가 노출될 것 같습니다.

2023-10-04 05:43 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/view/dto/StudyRecordsPageResponse.java
> +public record StudyRecordsPageResponse(List<StudyRecordResponse> studyRecords, PageInfoResponse pageInfo) {
따로 나눠주지 않고 `Page<StudyRecordResponse>` 를 반환하는 것은 어떻게 생각하시나요?

<img width="853" alt="image" src="https://github.com/woowacourse-teams/2023-haru-study/assets/35948985/07d20cee-4f7f-4588-84e1-89e9dc1b8a24">

이런식으로 프론트에서 내용은 content에서 꺼내 쓰고 페이지 관련 정보도 알아서 가져다 쓸 수 있어서 유연할 것 같습니다

2023-10-04 05:43 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/integration/PollingIntegrationTest.java
> -        System.out.println("jsonResponse = " + jsonResponse);
역시 문서왕 👍

2023-10-04 05:43 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
> +    private StudyRepository studyRepository;
사이에 한칸 띄워주시면 감사하겠습니다

2023-10-04 05:43 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/view/utils/LocalDateConverterTest.java
> +class LocalDateConverterTest {
테스트까지 꼼꼼하군요 👍

2023-10-04 05:57 UTC, woosung1223 requested changes
굿 고생했습니다 히어로상
덕분에 내 기록 조회 페이지가 든든해지겠네요~

자잘한 리뷰 남겼으니 확인 부탁드립니다!

2023-10-04 05:57 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/view/controller/ViewController.java
> +        );
이런 스타일도 보기는 좋지만 기존 코드와의 스타일 호환성은 아쉬운 것 같아요! 다음의 형태로 수정하는건 어떨까요!

```java

StudyRecordsPageResponse response = viewService.findStudyRecordsPage(memberId, page, size,
        startDate, endDate)

```

2023-10-04 05:57 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/view/dto/StudyRecordResponse.java
> +    public static StudyRecordResponse of(Study study) {
단일 인자인 경우에는 from을 사용하고 있었던 것 같아요!

2023-10-04 05:57 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/view/service/ViewService.java
> +                convertEndDate(endDate),
static 메소드인데 클래스명이 없어서 혼동의 여지가 있을 것 같아요! 클래스명을 선언해주는 쪽이 낫지 않을까요?

2023-10-04 05:57 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/view/utils/LocalDateConverter.java
> +    private static final LocalDateTime DEFAULT_START_DATETIME = LocalDateTime.of(2023, 7, 27, 0, 0, 0, 0);
시작일이 주어지지 않으면 7월 27일 이후로 생성된 스터디(모든 스터디)를 조회하는걸까요? 실제 날짜가 들어가니 조금 혼동의 여지가 있는 것 같은데 다른 표현 방식을 선택하면 어떨까요?

찾아보니 LocalDateTime.MIN이라는게 있더라구요!

2023-10-04 05:57 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
> +@Sql({"/import_dummy_studies.sql"})
저도 페이지네이션 구현하면서 dummy를 사용할까 하다가 BeforeEach를 사용하는 쪽으로 바꿨는데요.

이전에 저희가 SQL 파일을 유지보수하면서 겪었던 어려움들이 있었기 때문입니다. 매번 SQL 파일도 코드랑 같이 변경해주어야 하니까요!

따라서 아래처럼 @BeforeEach 절에서 더미 데이터를 넣는 방향은 어떨까요? (아래 코드는 실제 코드와 차이가 있을 수 있어요. 의미 전달용으로 간략하게 작성했습니다) 

```java
@BeforeEach
void setUp() {
        LocalDateTime localDateTime = LocalDateTime.of(2023, 07, 23);
        
        for (int i = 0; i < 100; i++) {
            entityManager.persist(new Study(localDateTime));
            localDateTime = localDateTime.plus(1L, DAYS);
        }
}
```

2023-10-04 11:29 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/controller/ViewController.java
> +            @RequestParam Integer size,
햐... 급하게 하다보니 이 부분을 놓쳤네요... 🤣 pageable로 받도록 수정함으로서 클라이언트에서 정렬 정보도 지정할 수 있도록 변경할 수 있어서 해당 방식으로 변경했습니다!

2023-10-04 11:44 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/dto/StudyRecordsPageResponse.java
> +public record StudyRecordsPageResponse(List<StudyRecordResponse> studyRecords, PageInfoResponse pageInfo) {
해당 방식이 사실은 가장 간단하기에 고려를 해보지 않았던 것은 아닙니다 😃 

하지만 이번에 구현한 API는 restful한 study를 반환하는게 아니라 `view 전용 API`를 만들어서 내어주는 것이었습니다.  그렇다보니 굳이 Pageable을 그대로 반환해서 범용성을 최대한 갖춰야만하는가에 대해서는 필요성을 상대적으로 덜 느꼈던 것 같습니다. 특정 view(페이지)에서 사용될 것이라고 생각하고 설계된 API이니까요.

그리고 클라이언트 입장에서 Pageable을 그대로 반환했을 때 응답해서 내려가는 값이 더 많아져서 더 복잡해질거라고 생각했습니다. 위에서 얘기했던 대로 스터디 기록 조회 `페이지를 위한 API` 였던지라 해당 부분은 클라이언트의 편의도 어느정도 고려되어도 좋겠다는 결론을 내리고 이렇게 구현하게 되었습니다.

만약 study를 restful하게 페이지 조회하는 API 였거나 처음부터 명세를 함께 진행했었다면 pageable을 반환하도록 설계했을 수도 있었을 것 같은데 이미 프론트 쪽에서도 구현을 마친 상태여서 큰 변화는 필수적인 이유가 아니라면 좀 피하고 싶기도 한게 가장 큰 이유이기는 하겠네요 ㅎㅎ

혹시 더 얘기해주실 부분이 있다면 코멘트 부탁드려요~

2023-10-04 11:58 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/view/dto/StudyRecordsPageResponse.java
> +public record StudyRecordsPageResponse(List<StudyRecordResponse> studyRecords, PageInfoResponse pageInfo) {
저도 뷰를 위한 api라서 최적화나 편의성도 이러한 방식이 낫고 프론트에 변경이 생기기 때문에 코멘트를 남길까 말까 고민을 했었습니다.
그래도 타당한 근거도 들어볼 수 있었고 직접 확인도 해보고 재밌었습니다.
지금 방식 그대로 가는 것도 찬성입니다 👍

2023-10-04 11:58 UTC, aak2075 approved these changes

2023-10-04 12:11 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/dto/StudyRecordResponse.java
> +    public static StudyRecordResponse of(Study study) {
Dto쪽 모두 반영완료했습니다!

2023-10-04 12:25 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/utils/LocalDateConverter.java
> +    private static final LocalDateTime DEFAULT_START_DATETIME = LocalDateTime.of(2023, 7, 27, 0, 0, 0, 0);
동의합니다! MIN이 존재하는지는 확인해보지 못했었네요 ㅎㅎ. 해당 방향으로 수정했습니다!

2023-10-04 12:32 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/service/ViewService.java
> +                convertEndDate(endDate),
음 요부분은 컨벤션 상 어떻게 처리하는게 나은 방식인지 좀 애매한 것 같긴 하네욤. 유틸 클래스 static import 시에는 클래스를 명시하는 방향으로 정하고 가는게 좋을까요?

2023-10-04 12:38 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
> +    private StudyRepository studyRepository;
요거 컨벤션 좀 안맞는 다른 테스트 코드도 함께 수정했습니당 ㅎㅎ

2023-10-04 12:43 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/dto/CalenderStudyRecordsResponse.java
> +        return new CalenderStudyRecordsResponse(clusteredByCreatedDate);
Collectors에 groupingBy라는 기능도 있었군요! 좋은 의견 제시 감사합니다 마코 👍 
하지만 마코가 말씀해주신대로 지금보다 가독성이 좀 떨어지는 것 같기는 해서... 지금 로직으로 유지해보겠습니다!

2023-10-04 15:55 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/view/service/ViewServiceTest.java
> +@Sql({"/import_dummy_studies.sql"})
BaseAuditing으로 삽입되는 createdDate를 원하는 값으로 더미데이터를 넣어줘야 했어서 고민을 많이 했던 부분이었습니다. 태오가 일러주신 방법을 맨 처음 고려해봤으나 BaseAuditing에서 @Column(updateable=true) 옵션을 줘서 해당 방법으로는 원하는대로 더미데이터를 넣을 수 없어 @Sql 어노테이션을 활용한 것이었습니다. 

그러나 태오와 슬랙에서 얘기를 나눴던 것처럼 entityManager.createQuery()를 통해 네이티브 쿼리로 직접 더미데이터의 createdDate를 갱신시켜주는 방향으로 리팩토링해봤습니다. 코드가 좀 난잡해진 것 같기는 한데 일단 불필요한 SQL파일은 없앨 수 있었네요... 🤣

2023-10-05 03:45 UTC, jaehee329 approved these changes
히이로 혼자 페이지네이션 공부하시면서 구현하시느라 고생하셨습니다!
앞의 다른 분들이 이미 리뷰를 한 번 해주셔서 그런지 이미 많이 다듬어졌네요~!

남긴 내용만 한번 살펴봐주세요!

2023-10-05 03:45 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
> +    );
page단위 조회처럼 order by를 위한 sort가 파라미터로 존재함을 메서드 이름으로 드러낼 필요는 없을까요?

2023-10-05 03:45 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/view/controller/ViewController.java
> +            @Authenticated AuthMember authMember,
여기와 기존의 study controller에도 사용하지 않는 authMember를 받고 있는데요,
authInterceptor를 거친 뒤에 파싱 작업이 다시 들어가게 되서 불필요하게 성능이 저하될 것 같아요
기존 것까지 사용하지 않는 authMember를 지워주실 수 있을까요? ㅎㅎㅎ

2023-10-05 03:45 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/view/service/ViewService.java
> +        );
범위 검색 후 오름차순 정렬로 이어지고 있는데요,
서비스 특성 상 데이터가 시간 기준 오름차순으로 삽입되고 이 규칙이 어떠한 동시성 문제에서든 깨질 일이 서비스상에서는 없지 않을까 하는 생각이 들어요. 아주 미묘한 차이로 발생한다고 해도 사용자가 살펴보았을 때 미리초 단위로 기록의 순서가 바껴서 이상하다는 생각이 들지도 않을 것 같고요.

정렬 자체가 비용이 큰 작업이다보니 확실한 방법이긴 하나 고민이 되네요 ㅎㅎ 어떻게 생각하시나요?

2023-10-05 03:54 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/view/service/ViewService.java
> +        );
당장은 그냥 넣어두는게 나을거같아요!

2023-10-05 06:43 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/study/repository/StudyRepository.java
> +    );
동의합니다! 팀에서 논의한대로 sortedBy를 네이밍에 추가하였습니다.

2023-10-05 07:22 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/controller/ViewController.java
> +            @Authenticated AuthMember authMember,
authMember는 이후에 자신이 진행한 스터디 이외에는 조회하지 못하도록 인가기능을 위해 받아뒀던 인자입니다. 일단 기능 구현이 더 먼저였어서 후순위로 미뤘었는데 말씀해주신김에 인가 기능까지 추가하였습니다!

2023-10-05 07:23 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/view/service/ViewService.java
> +        );
나중에 성능 테스트 진행 이후 데이터를 보고 개선하는 방향으로 해보시죠! 일단은 유지하도록 하겠습니다 😃

2023-10-05 07:53 UTC, woosung1223 approved these changes

2023-10-05 07:53 UTC, merged