[BE] CompositeOauthClient를 일급 컬렉션으로 변경
woowacourse-teams/2023-haru-study pull request #615
Opened 2023-10-04 13:04 UTC by aak2075

## 관련 이슈

- #605 

## 기존 코드의 문제

```java
public class CompositeOauthClient implements OauthClient {
    ...
    @Override
    public OauthTokenResponse requestOauthToken(String code, String providerName) {
        return getClient(providerName)
                .requestOauthToken(code, providerName);
    }
    ...
}
```
위와 같이 적절한 OauthClient를 찾기 위해 providerName을 파라미터로 받아야 하고, 이에 따라 인터페이스에서도 메서드의 파라미터에 providerName이 필요했습니다.

하지만 OauthClient의 구현 로직이 있는 KakaoOauthClient나 GoogleOauthClient는 requestOauthToken() 메서드 내에서는 providerName이 필요하지 않습니다.

이는 인터페이스가 구현체를 의존하게 된 상황이며 추상화가 조금 아쉽게 이루어졌다고 볼 수 있습니다.

이에 따라 `OauthProviderManager`를 추가하여 oauth provider 이름을 스레드에 저장하여 CompositeOauthClient에서 꺼내서 적절한 OauthClient를 찾도록 할 수 있습니다.

이러한 방식을 사용하면 인터페이스의 메소드 파라미터의 로직과는 상관 없는 providerName을 제거할 수 있습니다.

하지만, 스레드에 변수를 저장한다는 위험성(remove를 해주지 않으면 메모리 누수 발생)이 있기 때문에 이러한 추상화를 포기하고 안정성을 가져가는게 더 나을 수도 있어서 여러분의 의견을 듣고싶습니다.

미션을 하던 도중 TransactionSynchronizationManager 가 비슷한 상황에서 쓰이는 것을 보고 영감을 받아 시도해봤습니다.

추가로 개선한다면 setProviderName()과 clear()를 aop로 빼서 선언형으로 사용도 가능할 것 같네요

2023-10-04 13:29 UTC, woosung1223 commented
아주 맛있는 주제를 들고 찾아오셨군요 😋

해당 문제에 대해 저도 동감합니다. 
사실 providerName은 OauthClient 구현체의 관심사가 아닌데 추상화 레벨이 무너지는 것 같다는 생각이 드네요.

마코가 제안해주신 ThreadLocal을 사용한 방법은 정말 매력적이라 느껴집니다.

저도 이전에 '요청마다 생기는 웹 스코프 빈을 사용해서 해결할 수 없을까?' 라는 고민을 했었는데요.
ThreadLocal을 사용하는 방법도 좋은 것 같습니다!

그리고 저는 크게 위험하다고 생각이 들지도 않아요! remove만 있으면 메모리 누수 등 기타 문제가 발생할 염려도 없고, 설령 누가 실수로 지웠다고 하더라도 저희는 코드 리뷰 프로세스를 유지하고 있으니 그게 메인에 병합될 확률은 낮을 것이고요.

그래서 저는 approve를 드리려고 하는데 한 가지만 답변해주시면 좋을 것 같아요. 궁금한 점이 생겨서..

- 컴포지트 패턴을 꼭 적용해야 하는 이유가 있을까요?

컴포지트 패턴을 통해 재귀적인 트리구조를 구성할 수 있어서 좋다고 알고 있어요. 그런데 지금 컴포지트 패턴이 꼭 필요한지 의문이 생겼습니다. 
현재 구조를 보면 CompositeOauthClient만 OauthLoginFacade에서 참조되고 있고 GoogleOauthClient나 KakaoOauthClient는 CompositeOauthClient에서만 사용하는데요.

개별 객체(Kakao, Google)에 대한 참조를 하지 않고 CompositeOauthClient만 참조를 하는 것이라면 컴포지트 패턴보다는 일급 컬렉션을 사용하는게 맞지 않을까요? 개별 객체(Kakao, Google)만 참조되는 일이 있을까요?

일급 컬렉션을 사용하는 경우에는 마코가 말씀해주신 문제가 애초에 발생하지는 않을 것 같아서요!

2023-10-04 13:57 UTC, aak2075 commented
좋은 의견 감사합니다👍

저도 처음에는 일급 컬렉션을 고려했었는데요, 그 때는 List만 생각하고 Map은 생각하지 못했습니다 😅
그러다 보니 적절한 OauthClient를 찾는 책임을 분리하는 방법을 고민하다가 컴포지트 패턴을 생각하게 되었는데요, 여기에만 매몰되어 생각한 것 같습니다. 추상화를 했다고 하더라도 결국에는 OauthProviderManager의 도움을 받아야 하기 때문에 완벽하지는 않은 것 같습니다. 테오가 제시해준 방식이 훨씬 쉽고 관리하기도 좋을 것 같네요.
관짝에 넣겠습니다👋

2023-10-05 05:16 UTC, woosung1223 approved these changes
고생하셨습니다 마코~ 의견 제안해주신 덕분에 OauthClient 처리 로직이 더 좋은 방향으로 굳어진 것 같습니다 👍

2023-10-05 05:16 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
> +                .collect(Collectors.toMap(OauthClient::getProviderName, oauthClient -> oauthClient));
Collectors.toMap 깔끔하네요 굿

2023-10-05 05:16 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/integration/IntegrationTest.java
> +    private OauthClients oauthCLients;
여기 L이 대문자로 들어갔네요!

2023-10-05 05:18 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
> +                .collect(Collectors.toMap(OauthClient::getProviderName, oauthClient -> oauthClient));
이거 Function.identity() 쓸까요? 지금 봤는데

2023-10-05 05:18 UTC, jaehee329 requested changes
일급 컬렉션이 저희의 상황에선 좀 더 간결한 해결책이긴 하네요!
근데 프론트쪽 서브모듈 수정하신거같아서 RC합니다 ㅋㅋㅋㅋ

2023-10-05 05:18 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
> +                .collect(Collectors.toMap(OauthClient::getProviderName, oauthClient -> oauthClient));
이거 java17버전으로 깔끔하게 안되는부분인가요?

2023-10-05 05:20 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/domain/oauth/OauthClients.java
> +                .collect(Collectors.toMap(OauthClient::getProviderName, oauthClient -> oauthClient));
제가 아는건 toList() 밖에 없는데 방법이 또 있나요?

2023-10-05 05:22 UTC, MoonJeWoong approved these changes
앞선 크루들이 수정사항 남겨주셔서 저는 approve 하도록 할게요. 서브모듈 커밋만 수정해주세욤 ㅋㅋㅋ

2023-10-05 05:28 UTC, jaehee329 approved these changes

2023-10-05 05:33 UTC, merged