[BE] 코드 스타일 조정 및 리팩토링
woowacourse-teams/2023-haru-study pull request #717
Opened 2023-11-03 04:55 UTC by woosung1223

## 관련 이슈

- closed: #708 

## 구현 기능 및 변경 사항

- 비즈니스 로직까지 개선해보려고 하다가, 리뷰 비용이라든가 컨텍스트 일치 비용이 너무 클 것 같아서 스타일만 조정했습니다. 혹시 걸리는 부분 있다면 말씀해주세요~

## 스크린샷(선택)

2023-11-04 03:49 UTC, jaehee329 requested changes
짜잘한 변화 좋네요~
코멘트 남긴 부분에 대해서만 답변 부탁드려요! 저도 작은거 찾은거 여기에 PR 보내볼게요

2023-11-04 03:49 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/participant/domain/Participant.java
> +    public static Participant of(Study study, Member member, String nickname) {
of로 명명하면 participant 생성 시 content가 함께 영속화되는걸 놓칠 수 있어서 길게 이름지은 것으로 기억하는데요,
추후에 같은 애그리거트로 묶으면서 content에 대한 별개 접근이 필요하지 않은 시점에 함께 변경하는 것은 어떨까요?

2023-11-04 03:49 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/dto/TokenResponse.java
> +public record TokenResponse(String accessToken, @JsonIgnore UUID refreshToken, @JsonIgnore Long expireLength) {
응답의 형식이 달라지는데 유효기간이 추가된 이유가 있나요?

2023-11-04 03:49 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/content/service/ContentService.java
> +        validateParticipantIsCreatedByMember(authMember.id(), participant);
기존의 코드도 베스트는 아니지만 그나마 repository 접근 위치를 public 메서드 최상단에 모아볼 수 있다는 점에서 좋다고 생각해요.
member 객체가 이 메서드에서만 쓰이긴 하나 validation 메서드에서는 repository에서 객체 fetch에 대한 책임을 제외하는 편이 낫지 않을까요?

2023-11-04 04:52 UTC, jaehee329 commented
아 추가로 Admin 엔티티에 protected 빈 생성자가 없던데 당장은 괜찮아도 명시적으로 넣어두는게 안전할 것 같아요!

2023-11-06 10:25 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/auth/dto/TokenResponse.java
> +public record TokenResponse(String accessToken, @JsonIgnore UUID refreshToken, @JsonIgnore Long expireLength) {
@JsonIgnore를 붙이면 별도의 응답은 발생하지 않고, Service Layer에서 expireLength를 관리하기 위해 DTO로 넘겨줬습니다!

2023-11-06 10:30 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/participant/domain/Participant.java
> +    public static Participant of(Study study, Member member, String nickname) {
현재 Contents에 대한 초기화는 수행해주지 않고, `study.addParticipant` 만 추가적으로 호출해주는 것 같은데(연관관계 편의 메소드) `createParticipantOfStudy` 등과 같은 메소드명을 사용하는게 낫지 않을까요?

2023-11-06 10:32 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/content/service/ContentService.java
> +        validateParticipantIsCreatedByMember(authMember.id(), participant);
어느 정도 동감하는 부분입니다!

그런데 어쨌거나 검증용으로 Repository를 사용하는 것이라면 메소드 분리를 통해 메소드 책임을 적절하게 나누는 편이 낫지 않을까요? 만약 Repository 코드만 밖으로 뺀다면 검증 메소드를 수정하려할 때 밖에 있는 Repository 코드까지 바꿔야 할 수 있을 것 같아서요!

2023-11-06 10:34 UTC, aak2075 approved these changes
와 정말 많이 개선됐군요 고생하셨습니다 이러한 점진적인 리팩터링 너무 좋습니다👍

2023-11-06 11:37 UTC, MoonJeWoong approved these changes
저희가 없었던 사이 많은 것을 바꿔주셨군요 테오... 커밋 단위 잘 나눠주셔서 오랜만에 보는 데도 수월하게 볼 수 있었네요. 고생 많으셨습니다!

2023-11-06 11:37 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/content/service/ContentService.java
> +        validateParticipantIsCreatedByMember(authMember.id(), participant);
저는 개인적으로 repository 조회 로직이 검증을 위해 수행되고 있기 때문에 메서드로 함께 분리되는 편이 직관적이라고 생각합니다 :)

2023-11-06 11:37 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/participant/domain/Participant.java
> +    public static Participant of(Study study, Member member, String nickname) {
저희가 메서드 명을 지었던 당시에는 모디가 얘기해준 의미를 표시하기 위해 이렇게 작성했었는데 나중에 저희가 봐도 혼동의 여부가 존재하네요 ㅎㅎ... 지금 코드로 유지된다고 하면 메서드 명은 확실히 수정되는 쪽이 맞다고 생각합니다!

2023-11-06 11:37 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/content/service/ContentService.java
> +        validateParticipantBelongsToStudy(participant, studyId);
비즈니스 로직 개선 기가 막히네요 💯

2023-11-06 14:43 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/admin/AdminInterceptor.java
> +        if (isPreflightRequest(request)) {
오 그게 나을 것 같은데 이거는 다른 PR에서 한번에 하면 좋을 것 같아 이슈 파두겠습니다!

2023-11-07 00:07 UTC, jaehee329 approved these changes

2023-11-07 00:41 UTC, merged