[BE] 여러개의 쿼리파라미터를 ModelAttribute로 변경
woowacourse-teams/2023-haru-study pull request #719
Opened 2023-11-04 06:45 UTC by aak2075

## 관련 이슈

- ref: #716 
이전 리팩터링 pr에 추가로 Pr요청 보냅니다.

## 구현 기능 및 변경 사항

- 어제 모쌤이 ModelAttribute알려주셨는데 쿼리 파라미터에 유연하게 대응할 수 있겠다 싶어서 적용해 봤습니다.
- 추가로 해당 관련 부분 테스트 추가해 놓고 리팩터링 했습니다.

## 스크린샷(선택)

2023-11-06 07:12 UTC, woosung1223 requested changes
오 좋은 것 같습니다! 굿

필터링 조건이 걸려있는 API는 추후 필터링 조건이 추가되거나 하는 경우에 유연하게 대응할 수 있으니까 ModelAttribute를 활용하면 좋을 것 같아요!

다른 곳에도 적용하실거면 바로 해주셔도 좋을 것 같고 작업이 커질 것 같으면 나중에 해도 좋을 것 같네요~!

2023-11-06 07:12 UTC, woosung1223 approved these changes

2023-11-06 09:57 UTC, MoonJeWoong approved these changes
이제 스터디 필터링 조건이 추가된다고 하더라도 유연하게 대처할 수 있겠네요! 고생하셨습니다 👍

2023-11-06 10:20 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
> +    void 멤버_아이디와_참여_코드로_스터디를_조회한다() throws Exception {
네네 맞습니다.

2023-11-06 10:35 UTC, merged

2023-11-07 00:48 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/integration/StudyIntegrationTest.java
> +    void 멤버_아이디와_참여_코드로_스터디를_조회한다() throws Exception {
Controller 슬라이스 테스트가 있다면 거기에서 테스트하기 딱 좋은 부분일텐데 현재 저희 팀에서는 controller 테스트를 하고 있지 않아서 아쉽네요 ㅎㅎ... 일단 현상유지 하시는 걸로 하시죵!