[BE] JWT 토큰 사용 제거, Interceptor와 ArgumentResolver 중복 로직 제거
woowacourse-teams/2023-haru-study pull request #733
Opened 2023-11-14 10:02 UTC by jaehee329

## 관련 이슈

close #725 
## 구현 기능 및 변경 사항

- [x] 클라이언트쪽에서 JWT 토큰을 열어보지 않으므로 AES를 활용하는 방향으로 바꾼다.
- [x] Interceptor에서 파싱한 사용자 정보를 request에 넣어놓고 ArgumentResolver에서 필요하다면 가져오도록 바꾼다.

2023-11-14 10:47 UTC, aak2075 approved these changes
고생하셨습니다! 암호화하는 방법도 알게 되어서 좋았습니다.
catch하는 부분만 설명해 주시면 좋을 것 같아요!

2023-11-14 10:47 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +        } catch (Exception e) {
try-catch는 encrypt의 책임이 아닐까요? 그리고 구체적인 예외를 catch하는 것이 좋지 않을까요?

2023-11-14 10:47 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +        } catch (Exception e) {
여기도 Exception을 catch하고 있군요

2023-11-14 10:47 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +}
개행 부탁드립니다 🙏

2023-11-14 10:47 UTC, aak2075 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +        byte[] encrypted = cipher.doFinal(text.getBytes(StandardCharsets.UTF_8));
오오 이렇게 암호화 할 수 있군요 신기하네용👍

2023-11-14 11:01 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +        } catch (Exception e) {
여기는 uncheckedException과 checkedException 모든 상황에 대한 예외가 다양해서 구체적인 예외를 모두 나열하는 것이 필요가 없을 것 같아서 Exception으로 처리했어요.
예를 들어 ParseException은 CheckedException이고 RuntimeException을 상속한 저희의 커스텀 예외인 InvalidAccessTokenException 및 배열 크기 관련한 ArrayIndexOutOfBoundsException도 발생하고...

특히나 내부에서 InvalidAccessTokenException를 반환하는데 이를 다시 InvalidAccessTokenException으로 전달하는 것은 오히려 어색하지 않나 싶어서요. 또 Exception으로 모아도 잃는 stacktrace 정보도 없으니 괜찮지 않을까 했어요
예외에 대해선 여러 고민하고 하나로 묶은 것인데 그래도 구체적인 예외를 나열하는 편이 낫다고 생각하시나요?

2023-11-14 11:03 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +        } catch (Exception e) {
아래 댓글 달아주신 `parseSubject`메서드와 같은 구조로 외부에서 한 번에 예외를 잡아주는게 어떨까 했는데 다시 보니 예외를 발생시키는 경우가 `encrypt` 밖에 없어서 내부에서 해 주는게 맞겠네요~
encrypt 과정에서 굉장히 다양한 예외들이 발생하는데 GeneralSecurityException 정도로 묶어주겠습니다👍

2023-11-14 11:05 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +}
제 IDE와 깃헙에서는 괜찮아보이는데 다른 분들도 없는 것으로 보이면 말씀해주세요!

2023-11-16 08:03 UTC, MoonJeWoong requested changes
jwt 걷어내신다고 고생 많으셨습니다. 이런저런 궁금한 부분들 리뷰드려봤는데 확인 부탁드립니다!

2023-11-16 08:03 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +        } catch (Exception e) {
```suggestion
        } catch (ParseException |
                 GeneralSecurityException|
                 RuntimeException e) {
            throw new InvalidAccessTokenException(e);
        }
```

조금 번거롭더라도 이 코드를 나중에 보게될 저희 스스로를 위해서 catch문을 분리하는 것도 하나의 방법이 될 수 있지 않을까 제안해봅니다. 

그게 아니라면 개인적으로 private 검증 메서드마다 발생하는 checkedException에 대해서 예외 전환을 각각 해주는 편이 좋다고 생각이 들었어요. encrypt메서드의 경우는 이미 내부에서 예외를 런타임 예외로 전환해주고 있어서 크게 걸릴 부분은 없을 것 같은데 어떻게 생각하시나요?

2023-11-16 08:03 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +    }
encrypt 메서드는 내부에서 예외 전환을 해주는 방향으로 수정해주신 것 같아서 비슷한 방향으로 런타임 예외로 전환해주시면 좋을 것 같습니다. 😃

2023-11-16 08:44 UTC, jaehee329 commented
예외 핸들링 관련한 내용 추가 수정하고
tokenize하는 형태를 별도의 객체로 관리할 수 있도록 로직 추가 수정해볼게요~

2023-11-16 10:55 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +    private static final String iv = "0123456789abcdef"; // 16byte
오프라인으로 얘기하여 굳이 적용하지 않는 것으로...

2023-11-16 10:56 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +    }
말씀하신 예외가 더 깔끔할 것 같긴 한데 당장은 프론트랑 연계되는 내용이라 바로 반영은 어렵겠네요!😅

2023-11-16 10:57 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/util/AesTokenProvider.java
> +        } catch (Exception e) {
해당 부분은 별도 클래스에서 처리하도록 해서 예외들을 깔끔하게 처리했습니다!

추가로 확인해주세요~!

2023-11-16 10:59 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/auth/service/AuthService.java
> +                tokenConfig.refreshTokenExpireLength());
IDE 설정을 맞췄을텐데 저는 여기에서는 글자수가 길어서 그런지 자동으로 리포맷을 해주네요..😂

2023-11-16 10:59 UTC, jaehee329 commented
token 내용에 대한 추상화를 한 단계 높여서 예외 처리 로직이 깔끔해지도록 수정했습니다!

2023-11-18 14:15 UTC, woosung1223 approved these changes
고생하셨습니다~ 의존성이 줄어들어서 좋네요!

사소한 코멘트 남겼으니 확인 부탁드립니다.

2023-11-18 14:15 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/auth/util/AesTokenProviderTest.java
> +    private TokenConfig tokenConfig;
SpringBootTest가 필요하지 않을 것 같은데 어떻게 생각하시나요?

생성자로 ObjectMapper 넣어주면 단위테스트가 깔끔할 것 같네용

tokenConfig의 경우에도 테스트이므로 임의의 값으로 넣어주면 될 것 같습니다!
(테스트용 application.yml에도 임의의 값으로 정의되어 있기도 하고요)

2023-11-19 14:59 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/auth/util/AesTokenProviderTest.java
> +    private TokenConfig tokenConfig;
컨텍스트를 하나 덜 띄우는게 좋다는 말에 저도 당연히 동의합니다!
yml에서 테스트에서 쓰이는 설정에 대해 전역으로 관리되지 못하는 점이 조금 아쉽기는 하나 괜찮을 것 같아요.

다만 말씀하신 방법대로 실험해보니
```java
    private AesTokenProvider aesTokenProvider = new AesTokenProvider(new ObjectMapper());
```
스프링에서 주입해주는 ObjectMapper는 스프링만의 직렬화/역직렬화와 관련한 설정 클래스가 함께 포함되어있어
Jackson의 설정이 달라져 테스트가 완벽히 호환되지 않네요.(역직렬화 과정에서 예외)
스프링에서 어떻게 설정을 지정하는지 찾아보고 동일하게 만들어주어야 하는데 이는 당장 좀 오래 걸릴 듯 하고..
아니면 프로덕션 코드를 테스트에 의존적으로 조금 바꿔주어야 하네요 🥲

혹시 아시는 방법 있으신가요?

2023-11-19 15:57 UTC, woosung1223 commented on backend/src/test/java/harustudy/backend/auth/util/AesTokenProviderTest.java
> +    private TokenConfig tokenConfig;
조금 찾아보니 스프링에서 주입해주는 ObjectMapper가 `new ObjectMapper()` 로 생성한 인스턴스와 다른 점이 있긴 있네요 ㄷㄷㄷ..(처음 암)

Gradle의 java 플러그인에서 `parameters` 옵션을 제공해주고, Spring Boot가 이를 사용해 auto configure를 하는군요..! 그래서 말씀해주신대로 부가 기능이 조금씩 달라지는 것 같습니다~!

그런데 제가 클론받아서 실험해보니, `@RequiredArgsConstructor`를 제거하고 `@NoArgsConstructor`를 붙이면 정상적으로 리플렉션을 사용한 역직렬화가 동작하는 것 같더라고요. 

현재는 굳이 Spring Boot만의 추가 기능이 필요하지 않은 상황이므로 DI를 활용하지 않아도 될 것 같은데 어떻게 생각하시나요?

그리고 ObjectMapper를 인스턴스 변수로 선언해 여러 스레드가 공유하게 하는 건 지양하라는 아티클도 본 적 있네여!
https://stackoverflow.com/questions/3907929/should-i-declare-jacksons-objectmapper-as-a-static-field

2023-11-21 02:16 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/auth/util/AesTokenProviderTest.java
> +    private TokenConfig tokenConfig;
=> 팀 회의에서 별도의 이슈에서 테스트 ObjectMapper에 대한 처리를 하도록 결정했습니다.

2023-11-21 02:16 UTC, MoonJeWoong commented on backend/src/test/java/harustudy/backend/auth/util/AesTokenProviderTest.java
> +    private TokenConfig tokenConfig;
요거 테오와 얘기하면서 정리된 부분이 있는데 해당 PR은 일단 merge하고 테스트 최적화 관련 이슈를 발행해서 따로 작업하는 편이 좋을 듯 합니다!

2023-11-21 02:17 UTC, MoonJeWoong approved these changes

2023-11-21 02:17 UTC, merged