[BE] 스터디 정보 조회 기능 구현
woowacourse-teams/2023-haru-study pull request #97
Opened 2023-07-18 05:39 UTC by MoonJeWoong

## 관련 이슈

- closed #59 

## 구현 기능 및 변경 사항

## 추가할 기능

- [ ] 스터디에 속하는 특정 멤버에 대한 정보를 조회할 수 있다.
    - 스터디 아이디와 멤버 아이디를 통해 다음의 항목을 조회할 수 있다.
        - 스터디 이름, 스터디 총 사이클, 사이클 당 학습시간, 멤버의 현재 사이클, 멤버의 진행 상태

- [ ] 스터디 메타데이터 및 참여한 모든 스터디원에 대한 정보를 조회할 수 있다.
    - 스터디 아이디를 통해 다음의 항목을 조회할 수 있다.
        - 스터디 이름, 스터디 총 사이클, 사이클 당 학습시간, 전체 스터디원 닉네임 리스트  

- [ ] 스터디에 참여한 특정 스터디원의 콘텐츠를 조회할 수 있다.
    - 특정 멤버에 대해 다음과 같은 항목을 조회할 수 있다.
        - 현재까지 진행한 사이클 정보 리스트
            - 사이클 정보는 사이클 번호, 계획, 회고를 포함한다.
        
- [x] 멤버는 현재 사이클의 계획을 조회할 수 있다.

- 예외 상황
  - [ ] 존재하지 않는 스터디를 조회하면 예외를 반환한다.
  - [ ] 스터디에 참여하지 않은 멤버를 조회하면 예외를 반환한다.

---

일단 구현된 부분만 푸시했습니다.

2023-07-18 13:22 UTC, woosung1223 reviewed
조회 쉽지 않은데 고생하셨습니다 👍

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/entity/PomodoroProgress.java
> +                .orElseThrow(IllegalArgumentException::new);
커스텀 예외 사용이 추후 예외 핸들링하기 좋아보이는데 어떻게 생각하세요?

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/repository/dto/MapToStringConverter.java
> +
Converter의 경우 양방향 매핑(Map -> String, String -> Map)이기 때문에 객체명을 수정할 필요가 있어보입니다!

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/repository/MemberProgressRepository.java
> +                select mp from MemberProgress mp
Java 17 기능 사용 👍

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/repository/MemberProgressRepository.java
> +
요거 논의해볼만한 부분인데, ID로 찾을지 객체로 찾을지 결정해봐야 할 것 같아요.
현재 이 코드에서는 `studyId`, `memberId`로 찾고 있는데 저는 객체로 탐색하는게 JPA 사상에 맞는거같아서 `Study`, `Member`를 통해
find하도록 설정했거든요. 그런데 이 경우에 select 쿼리가 더 나가긴 합니다!

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/service/PomodoroProgressService.java
> +        if (pomodoroProgresses.size() == 0) {
`isEmpty()` 를 사용하면 더욱 깔끔해질 것 같네요~

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/service/PomodoroProgressService.java
> +        Pomodoro pomodoro = (Pomodoro) pomodoroProgresses.get(0).getStudy();
`get(0)`는 어떤 의미인가요?! 멤버 한 명당 `pomodoroProgress`가 하나인 것으로 생각되는데(지금의 경우에는)
추후 확장을 대비해 List형태로 반환하는걸까요?

만약 그렇다면 Repository에서 SingleResult만 반환하는 메소드를 하나 더 추가로 만들어 사용하는 편이 낫지 않을까요?

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/service/PomodoroProgressService.java
> +                .toList();
Java 17 활용 👍

2023-07-18 13:22 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/controller/StudyController.java
> +            @RequestParam Long memberId) {
cycle, memberId의 경우 null이 들어올 수도 있지 않을까요?
Bean Validation을 적용해도 좋을 것 같습니다~

2023-07-19 00:38 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/controller/StudyController.java
> +    public ResponseEntity<CurrentCyclePlanResponse> findCurrentCyclePlan(
현재 URI가 `/api/studies/{studyId}/content/plans`로 되어 있습니다.
그런데 단일 멤버 content 조회 URI는 `/api/studies/{studyId}/members/{memberId}/content`로 되어 있어서 URI 계층 구조에 일관성이 떨어지는데 이 부분을 먼저 수정하고 어떤 controller에 남길지 얘기해보면 좋을 것 같습니다.

2023-07-19 00:50 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/dto/response/MemberStudyMetaDataResponse.java
> +    }
@JsonCreator 어노테이션을 제거해도 역직렬화가 잘 되는 것을 확인해서 삭제처리 했습니다.

2023-07-19 00:55 UTC, MoonJeWoong commented on backend/src/main/java/harustudy/backend/entity/PomodoroProgress.java
> +                .orElseThrow(IllegalArgumentException::new);
추후 에러코드 정의도 해야한다고 생각했었어서 그 때 정의하면서 추가하도록 할 계획입니다.

2023-07-19 01:17 UTC, jaehee329 requested changes
고민 같이 좀 해보면 좋을거같아요~

2023-07-19 01:17 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/controller/StudyController.java
> +            @RequestParam Long memberId) {
컨트롤러의 모든 파라미터에 대해 nullity 체크를 어떻게든 진행해야 할 것 같아요!

2023-07-19 01:17 UTC, jaehee329 commented on backend/src/main/java/harustudy/backend/repository/MemberProgressRepository.java
> +
이건 제 개인적인 생각인데 단건 쿼리 몇 회 더 나가는거라 사실 두 방법 다 성능적으로 크게 차이날 것 같지는 않아요~
하지만 JPA 사용 스타일에 대해서는 비슷하게 가져가야 할 것 같아서 맞춰보면 될 것 같아요

2023-07-19 01:17 UTC, jaehee329 commented on backend/src/test/java/harustudy/backend/integration/FindStudyIntegrationTest.java
> +                        get("/api/studies/1/members/1/content")
@Sql을 쓰고 있는데 첫 데이터니까 1번일거라 예상되기는 한데 `1`을 써도 될지..? 고민이 되네요

2023-07-19 02:26 UTC, woosung1223 commented on backend/src/main/java/harustudy/backend/repository/MemberProgressRepository.java
> +
레포지토리에서 여러 도메인을 참조하는 경우 도메인 영역 간 결합도가 너무 커져서 유지보수하기 어려울 것 같아요
따라서 같은 도메인 영역이라면 엔티티로 조회, 다른 도메인 영역이라면 ID를 사용하는 편이 나을 것 같습니다(경험은 아직 없지만)

하지만 아직 문제가 발생한 건 아니니 마코 말대로 모두 엔티티 조회하도록 변경해놓고 상황을 지켜보는 편이 좋을 것 같네요~

2023-07-19 02:59 UTC, aak2075 commented on backend/src/test/java/harustudy/backend/integration/FindStudyIntegrationTest.java
> +                        get("/api/studies/1/members/1/content")
현재는 save가 없어서 나중에 save생기면 fixture로 수정하겠습니다!

2023-07-19 04:30 UTC, woosung1223 approved these changes

2023-07-19 04:31 UTC, jaehee329 approved these changes
굿

2023-07-19 04:51 UTC, merged